/**
* This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#pragma once
// System headers
#include <nlohmann/json.hpp>
#include <optional>
#include <string>
#include <vector>
#include "Category.h"
#include "Tag.h"



namespace models {


class Pet
{
public:
    enum class StatusEnum {
        UNSPECIFIED,
        AVAILABLE,
        PENDING,
        SOLD
    };

    // Enum conversion functions (definitions in .cpp)
    static std::string StatusEnumToString(StatusEnum value);
    static StatusEnum StatusEnumFromString(const std::string& str);


    Pet();
    virtual ~Pet() = default;

    // Getters and setters
    [[nodiscard]] long getId() const;
    void setId(const long& id);
    [[nodiscard]] Category getCategory() const;
    void setCategory(const Category& category);
    [[nodiscard]] std::string getName() const;
    void setName(const std::string& name);
    [[nodiscard]] std::vector<std::string> getPhotoUrls() const;
    void setPhotoUrls(const std::vector<std::string>& photoUrls);
    [[nodiscard]] std::vector<Tag> getTags() const;
    void setTags(const std::vector<Tag>& tags);
    [[nodiscard]] std::optional<StatusEnum> getStatus() const;
    void setStatus(const std::optional<StatusEnum>& status);
    // Serialization helpers for std::optional<StatusEnum>
    friend inline void to_json(nlohmann::json& j, const std::optional<StatusEnum>& opt)
    {
        if (opt.has_value())
        {
            j = StatusEnumToString(opt.value());
        }
        else
        {
            j = nullptr;
        }
    }

    friend inline void from_json(const nlohmann::json& j, std::optional<StatusEnum>& opt)
    {
        if (j.is_null())
        {
            opt = std::nullopt;
        }
        else
        {
            opt = StatusEnumFromString(j.get<std::string>());
        }
    }



    // JSON serialization using NLOHMANN INTRUSIVE macro (must be inside class to access private members)
    NLOHMANN_DEFINE_TYPE_INTRUSIVE(Pet,
         id, category, name, photoUrls, tags, status)

private:
    long id;
    Category category;
    std::string name;
    std::vector<std::string> photoUrls;
    std::vector<Tag> tags;
    std::optional<StatusEnum> status;
};


} // namespace models

