
/**
* This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
#include "User.h"

namespace models {

User::User()
: id(0)
, username("")
, firstName("")
, lastName("")
, email("")
, password("")
, phone("")
, userStatus(0)
{
}
// =========================================
// ===== Getters/Setters =====
// =========================================
// ===================
// ===== Getters =====
// ===================
long User::getId() const
{
    return id;
}
std::string User::getUsername() const
{
    return username;
}
std::string User::getFirstName() const
{
    return firstName;
}
std::string User::getLastName() const
{
    return lastName;
}
std::string User::getEmail() const
{
    return email;
}
std::string User::getPassword() const
{
    return password;
}
std::string User::getPhone() const
{
    return phone;
}
int User::getUserStatus() const
{
    return userStatus;
}

// ===================
// ===== Setters =====
// ===================
void User::setId(const long& idObj)
{
    id = idObj;
}
void User::setUsername(const std::string& usernameObj)
{
    username = usernameObj;
}
void User::setFirstName(const std::string& firstNameObj)
{
    firstName = firstNameObj;
}
void User::setLastName(const std::string& lastNameObj)
{
    lastName = lastNameObj;
}
void User::setEmail(const std::string& emailObj)
{
    email = emailObj;
}
void User::setPassword(const std::string& passwordObj)
{
    password = passwordObj;
}
void User::setPhone(const std::string& phoneObj)
{
    phone = phoneObj;
}
void User::setUserStatus(const int& userStatusObj)
{
    userStatus = userStatusObj;
}






} // namespace models

