/**
* This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#pragma once
// System headers
#include <nlohmann/json.hpp>
#include <cstdint>
#include <string>



namespace models {


class User
{
public:

    User();
    virtual ~User() = default;

    // Getters and setters
    [[nodiscard]] long getId() const;
    void setId(const long& id);
    [[nodiscard]] std::string getUsername() const;
    void setUsername(const std::string& username);
    [[nodiscard]] std::string getFirstName() const;
    void setFirstName(const std::string& firstName);
    [[nodiscard]] std::string getLastName() const;
    void setLastName(const std::string& lastName);
    [[nodiscard]] std::string getEmail() const;
    void setEmail(const std::string& email);
    [[nodiscard]] std::string getPassword() const;
    void setPassword(const std::string& password);
    [[nodiscard]] std::string getPhone() const;
    void setPhone(const std::string& phone);
    [[nodiscard]] int getUserStatus() const;
    void setUserStatus(const int& userStatus);


    // JSON serialization using NLOHMANN INTRUSIVE macro (must be inside class to access private members)
    NLOHMANN_DEFINE_TYPE_INTRUSIVE(User,
         id, username, firstName, lastName, email, password, phone, userStatus)

private:
    long id;
    std::string username;
    std::string firstName;
    std::string lastName;
    std::string email;
    std::string password;
    std::string phone;
    int userStatus;
};


} // namespace models

