/**
* This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

// System headers
#include <algorithm>
#include <cctype>
#include <locale>

// Project headers
#include "PetApi.h"
#include "AuthenticationManager.h"

constexpr int HTTP_RESPONSE_CODE_PET = 200;
constexpr int HTTP_RESPONSE_CODE_API_RESPONSE = 200;
constexpr int HTTP_RESPONSE_CODE_NO_CONTENT = 204;
constexpr int HTTP_RESPONSE_CODE_BAD_REQUEST = 400;
constexpr int HTTP_RESPONSE_CODE_UNAUTHORIZED = 401;
constexpr int HTTP_RESPONSE_CODE_INTERNAL_SERVER_ERROR = 500;

namespace Api {

using namespace models;

bool Pet::parsePetPostParams(const httplib::Request& req, Pet::PetPostRequest& params, std::vector<std::string>& paramErrors)
{
    std::vector<std::string> errors;

    if (!req.body.empty())
    {
        try
        {
            nlohmann::json json = nlohmann::json::parse(req.body);
            from_json(json, params.m_request);
        }
        catch (const std::exception& e)
        {
            errors.push_back("Invalid request body: " + std::string(e.what()));
        }
    }
    else
    {
        errors.push_back("Missing required request body");
    }

    // Return errors via out-parameter, return false if any errors
    if (!errors.empty())
    {
        paramErrors = std::move(errors);
        return false;
    }
    return true;
}
void Pet::handlePetPostResponse(const PetPostResponse& result, httplib::Response& res)
{
    // Single response type
    res.status = HTTP_RESPONSE_CODE_PET;
    nlohmann::json responseJson;
    to_json(responseJson, result);
    res.set_content(responseJson.dump(), "application/json");
}
bool Pet::parsePetpetIdDeleteParams(const httplib::Request& req, Pet::PetpetIdDeleteRequest& params, std::vector<std::string>& paramErrors)
{
    std::vector<std::string> errors;

    // Header Parameters - api_key
    if (!req.get_header_value("api_key").empty())
    {
        params.m_apiKey = req.get_header_value("api_key");
    }
    else
    {
        // Use default value for optional parameter
        params.m_apiKey = "";
    }

    // Path Parameters - petId (index: 1)
    if (req.matches.size() < 1 + 1)
    {
        errors.push_back("Missing path parameter 'petId'");
    }
    else
    {
        try
        {
            params.m_petId = std::stoll(req.matches[1]);
        }
        catch (const std::exception& e)
        {
            errors.push_back("Invalid path parameter 'petId': " + std::string(e.what()));
        }
    }

    // Return errors via out-parameter, return false if any errors
    if (!errors.empty())
    {
        paramErrors = std::move(errors);
        return false;
    }
    return true;
}
bool Pet::parsePetfindByStatusGetParams(const httplib::Request& req, Pet::PetfindByStatusGetRequest& params, std::vector<std::string>& paramErrors)
{
    std::vector<std::string> errors;

    // Query Parameters - status
    if (req.has_param("status"))
    {
        try
        {
            // form/simple: multi-param or comma-separated
            size_t count = req.get_param_value_count("status");
            if (count > 1)
            {
                for (size_t i = 0; i < count; ++i)
                {
                    auto val = req.get_param_value("status", i);

                    params.m_status.emplace_back(val);

                }
            }
            else if (count == 1)
            {
                auto val = req.get_param_value("status", 0);
                std::stringstream ss(val);
                std::string item;
                while (std::getline(ss, item, ','))
                {
                    if (!item.empty())
                    {

                        params.m_status.emplace_back(item);

                    }
                }
            }
        }
        catch (const std::exception& e)
        {
            errors.push_back("Invalid query parameter 'status': " + std::string(e.what()));
        }
    }

    // Return errors via out-parameter, return false if any errors
    if (!errors.empty())
    {
        paramErrors = std::move(errors);
        return false;
    }
    return true;
}
void Pet::handlePetfindByStatusGetResponse(const PetfindByStatusGetResponse& result, httplib::Response& res)
{
    // Single response type
    res.status = HTTP_RESPONSE_CODE_PET;
    nlohmann::json responseJson;
    to_json(responseJson, result);
    res.set_content(responseJson.dump(), "application/json");
}
bool Pet::parsePetfindByTagsGetParams(const httplib::Request& req, Pet::PetfindByTagsGetRequest& params, std::vector<std::string>& paramErrors)
{
    std::vector<std::string> errors;

    // Query Parameters - tags
    if (req.has_param("tags"))
    {
        try
        {
            // form/simple: multi-param or comma-separated
            size_t count = req.get_param_value_count("tags");
            if (count > 1)
            {
                for (size_t i = 0; i < count; ++i)
                {
                    auto val = req.get_param_value("tags", i);

                    params.m_tags.emplace_back(val);

                }
            }
            else if (count == 1)
            {
                auto val = req.get_param_value("tags", 0);
                std::stringstream ss(val);
                std::string item;
                while (std::getline(ss, item, ','))
                {
                    if (!item.empty())
                    {

                        params.m_tags.emplace_back(item);

                    }
                }
            }
        }
        catch (const std::exception& e)
        {
            errors.push_back("Invalid query parameter 'tags': " + std::string(e.what()));
        }
    }

    // Return errors via out-parameter, return false if any errors
    if (!errors.empty())
    {
        paramErrors = std::move(errors);
        return false;
    }
    return true;
}
void Pet::handlePetfindByTagsGetResponse(const PetfindByTagsGetResponse& result, httplib::Response& res)
{
    // Single response type
    res.status = HTTP_RESPONSE_CODE_PET;
    nlohmann::json responseJson;
    to_json(responseJson, result);
    res.set_content(responseJson.dump(), "application/json");
}
bool Pet::parsePetpetIdGetParams(const httplib::Request& req, Pet::PetpetIdGetRequest& params, std::vector<std::string>& paramErrors)
{
    std::vector<std::string> errors;

    // Path Parameters - petId (index: 1)
    if (req.matches.size() < 1 + 1)
    {
        errors.push_back("Missing path parameter 'petId'");
    }
    else
    {
        try
        {
            params.m_petId = std::stoll(req.matches[1]);
        }
        catch (const std::exception& e)
        {
            errors.push_back("Invalid path parameter 'petId': " + std::string(e.what()));
        }
    }

    // Return errors via out-parameter, return false if any errors
    if (!errors.empty())
    {
        paramErrors = std::move(errors);
        return false;
    }
    return true;
}
void Pet::handlePetpetIdGetResponse(const PetpetIdGetResponse& result, httplib::Response& res)
{
    // Single response type
    res.status = HTTP_RESPONSE_CODE_PET;
    nlohmann::json responseJson;
    to_json(responseJson, result);
    res.set_content(responseJson.dump(), "application/json");
}
bool Pet::parsePetPutParams(const httplib::Request& req, Pet::PetPutRequest& params, std::vector<std::string>& paramErrors)
{
    std::vector<std::string> errors;

    if (!req.body.empty())
    {
        try
        {
            nlohmann::json json = nlohmann::json::parse(req.body);
            from_json(json, params.m_request);
        }
        catch (const std::exception& e)
        {
            errors.push_back("Invalid request body: " + std::string(e.what()));
        }
    }
    else
    {
        errors.push_back("Missing required request body");
    }

    // Return errors via out-parameter, return false if any errors
    if (!errors.empty())
    {
        paramErrors = std::move(errors);
        return false;
    }
    return true;
}
void Pet::handlePetPutResponse(const PetPutResponse& result, httplib::Response& res)
{
    // Single response type
    res.status = HTTP_RESPONSE_CODE_PET;
    nlohmann::json responseJson;
    to_json(responseJson, result);
    res.set_content(responseJson.dump(), "application/json");
}
bool Pet::parsePetpetIdPostParams(const httplib::Request& req, Pet::PetpetIdPostRequest& params, std::vector<std::string>& paramErrors)
{
    std::vector<std::string> errors;

    // Path Parameters - petId (index: 1)
    if (req.matches.size() < 1 + 1)
    {
        errors.push_back("Missing path parameter 'petId'");
    }
    else
    {
        try
        {
            params.m_petId = std::stoll(req.matches[1]);
        }
        catch (const std::exception& e)
        {
            errors.push_back("Invalid path parameter 'petId': " + std::string(e.what()));
        }
    }

    // Return errors via out-parameter, return false if any errors
    if (!errors.empty())
    {
        paramErrors = std::move(errors);
        return false;
    }
    return true;
}
bool Pet::parsePetpetIduploadImagePostParams(const httplib::Request& req, Pet::PetpetIduploadImagePostRequest& params, std::vector<std::string>& paramErrors)
{
    std::vector<std::string> errors;

    // Path Parameters - petId (index: 1)
    if (req.matches.size() < 1 + 1)
    {
        errors.push_back("Missing path parameter 'petId'");
    }
    else
    {
        try
        {
            params.m_petId = std::stoll(req.matches[1]);
        }
        catch (const std::exception& e)
        {
            errors.push_back("Invalid path parameter 'petId': " + std::string(e.what()));
        }
    }

    // Return errors via out-parameter, return false if any errors
    if (!errors.empty())
    {
        paramErrors = std::move(errors);
        return false;
    }
    return true;
}
void Pet::handlePetpetIduploadImagePostResponse(const PetpetIduploadImagePostResponse& result, httplib::Response& res)
{
    // Single response type
    res.status = HTTP_RESPONSE_CODE_API_RESPONSE;
    nlohmann::json responseJson;
    to_json(responseJson, result);
    res.set_content(responseJson.dump(), "application/json");
}

bool Pet::performAuthentication(
    const httplib::Request& req,
    std::shared_ptr<AuthenticationManager> auth,
    httplib::Response& res)
{
    if (!auth)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "AuthenticationManager not configured";
        res.status = HTTP_RESPONSE_CODE_INTERNAL_SERVER_ERROR;
        res.set_content(errorJson.dump(), "application/json");
        return false;
    }

    if (req.has_header("api_key"))
    {
        if (auth->validateApiKey(req.get_header_value("api_key"))) return true;
    }



    if (req.has_header("Authorization"))
    {
        auto authHeader = req.get_header_value("Authorization");
        if (authHeader.find("Bearer ") == 0)
        {
            std::string token = authHeader.substr(7);
            std::vector<std::string> requiredScopes = { "write:pets", "read:pets" };
            if (auth->validateOAuth2(token, requiredScopes)) return true;
        }
    }

    return false;
}

void Pet::handlePetPostRequest([[maybe_unused]] const httplib::Request& req, httplib::Response& res, std::shared_ptr<AuthenticationManager> auth)
{
    try
    {
        if (!performAuthentication(req, auth, res))
        {
            nlohmann::json errorJson = nlohmann::json::object();
            errorJson["message"] = "Authentication required";
            res.status = HTTP_RESPONSE_CODE_UNAUTHORIZED;
            res.set_content(errorJson.dump(), "application/json");
            return;
        }

        PetPostRequest params;
        std::vector<std::string> paramErrors;
        if (!parsePetPostParams(req, params, paramErrors))
        {
            nlohmann::json errorJson = nlohmann::json::object();
            errorJson["message"] = "Invalid parameters";
            errorJson["errors"] = paramErrors;
            res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
            res.set_content(errorJson.dump(), "application/json");
            return;
        }
        auto result = handlePostForPet(params);
        handlePetPostResponse(result, res);

    }
    catch (const nlohmann::json::parse_error& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Invalid JSON: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
        res.set_content(errorJson.dump(), "application/json");
    }
    catch (const nlohmann::json::invalid_iterator& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Invalid JSON: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
        res.set_content(errorJson.dump(), "application/json");
    }
    catch (const nlohmann::json::type_error& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Invalid JSON: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
        res.set_content(errorJson.dump(), "application/json");
    }
    catch (const nlohmann::json::out_of_range& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Invalid JSON: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
        res.set_content(errorJson.dump(), "application/json");
    }
    catch (const nlohmann::json::other_error& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Invalid JSON: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
        res.set_content(errorJson.dump(), "application/json");
    }
}

void Pet::handlePetpetIdDeleteRequest([[maybe_unused]] const httplib::Request& req, httplib::Response& res, std::shared_ptr<AuthenticationManager> auth)
{
    try
    {
        if (!performAuthentication(req, auth, res))
        {
            nlohmann::json errorJson = nlohmann::json::object();
            errorJson["message"] = "Authentication required";
            res.status = HTTP_RESPONSE_CODE_UNAUTHORIZED;
            res.set_content(errorJson.dump(), "application/json");
            return;
        }

        PetpetIdDeleteRequest params;
        std::vector<std::string> paramErrors;
        if (!parsePetpetIdDeleteParams(req, params, paramErrors))
        {
            nlohmann::json errorJson = nlohmann::json::object();
            errorJson["message"] = "Invalid parameters";
            errorJson["errors"] = paramErrors;
            res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
            res.set_content(errorJson.dump(), "application/json");
            return;
        }

        handleDeleteForPetpetId(params);
        res.status = HTTP_RESPONSE_CODE_NO_CONTENT;

    }
    catch (const std::exception& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Internal error: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_INTERNAL_SERVER_ERROR;
        res.set_content(errorJson.dump(), "application/json");
    }
}

void Pet::handlePetfindByStatusGetRequest([[maybe_unused]] const httplib::Request& req, httplib::Response& res, std::shared_ptr<AuthenticationManager> auth)
{
    try
    {
        if (!performAuthentication(req, auth, res))
        {
            nlohmann::json errorJson = nlohmann::json::object();
            errorJson["message"] = "Authentication required";
            res.status = HTTP_RESPONSE_CODE_UNAUTHORIZED;
            res.set_content(errorJson.dump(), "application/json");
            return;
        }

        PetfindByStatusGetRequest params;
        std::vector<std::string> paramErrors;
        if (!parsePetfindByStatusGetParams(req, params, paramErrors))
        {
            nlohmann::json errorJson = nlohmann::json::object();
            errorJson["message"] = "Invalid parameters";
            errorJson["errors"] = paramErrors;
            res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
            res.set_content(errorJson.dump(), "application/json");
            return;
        }
        auto result = handleGetForPetfindByStatus(params);
        handlePetfindByStatusGetResponse(result, res);

    }
    catch (const std::exception& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Internal error: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_INTERNAL_SERVER_ERROR;
        res.set_content(errorJson.dump(), "application/json");
    }
}

void Pet::handlePetfindByTagsGetRequest([[maybe_unused]] const httplib::Request& req, httplib::Response& res, std::shared_ptr<AuthenticationManager> auth)
{
    try
    {
        if (!performAuthentication(req, auth, res))
        {
            nlohmann::json errorJson = nlohmann::json::object();
            errorJson["message"] = "Authentication required";
            res.status = HTTP_RESPONSE_CODE_UNAUTHORIZED;
            res.set_content(errorJson.dump(), "application/json");
            return;
        }

        PetfindByTagsGetRequest params;
        std::vector<std::string> paramErrors;
        if (!parsePetfindByTagsGetParams(req, params, paramErrors))
        {
            nlohmann::json errorJson = nlohmann::json::object();
            errorJson["message"] = "Invalid parameters";
            errorJson["errors"] = paramErrors;
            res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
            res.set_content(errorJson.dump(), "application/json");
            return;
        }
        auto result = handleGetForPetfindByTags(params);
        handlePetfindByTagsGetResponse(result, res);

    }
    catch (const std::exception& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Internal error: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_INTERNAL_SERVER_ERROR;
        res.set_content(errorJson.dump(), "application/json");
    }
}

void Pet::handlePetpetIdGetRequest([[maybe_unused]] const httplib::Request& req, httplib::Response& res, std::shared_ptr<AuthenticationManager> auth)
{
    try
    {
        if (!performAuthentication(req, auth, res))
        {
            nlohmann::json errorJson = nlohmann::json::object();
            errorJson["message"] = "Authentication required";
            res.status = HTTP_RESPONSE_CODE_UNAUTHORIZED;
            res.set_content(errorJson.dump(), "application/json");
            return;
        }

        PetpetIdGetRequest params;
        std::vector<std::string> paramErrors;
        if (!parsePetpetIdGetParams(req, params, paramErrors))
        {
            nlohmann::json errorJson = nlohmann::json::object();
            errorJson["message"] = "Invalid parameters";
            errorJson["errors"] = paramErrors;
            res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
            res.set_content(errorJson.dump(), "application/json");
            return;
        }
        auto result = handleGetForPetpetId(params);
        handlePetpetIdGetResponse(result, res);

    }
    catch (const std::exception& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Internal error: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_INTERNAL_SERVER_ERROR;
        res.set_content(errorJson.dump(), "application/json");
    }
}

void Pet::handlePetPutRequest([[maybe_unused]] const httplib::Request& req, httplib::Response& res, std::shared_ptr<AuthenticationManager> auth)
{
    try
    {
        if (!performAuthentication(req, auth, res))
        {
            nlohmann::json errorJson = nlohmann::json::object();
            errorJson["message"] = "Authentication required";
            res.status = HTTP_RESPONSE_CODE_UNAUTHORIZED;
            res.set_content(errorJson.dump(), "application/json");
            return;
        }

        PetPutRequest params;
        std::vector<std::string> paramErrors;
        if (!parsePetPutParams(req, params, paramErrors))
        {
            nlohmann::json errorJson = nlohmann::json::object();
            errorJson["message"] = "Invalid parameters";
            errorJson["errors"] = paramErrors;
            res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
            res.set_content(errorJson.dump(), "application/json");
            return;
        }
        auto result = handlePutForPet(params);
        handlePetPutResponse(result, res);

    }
    catch (const nlohmann::json::parse_error& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Invalid JSON: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
        res.set_content(errorJson.dump(), "application/json");
    }
    catch (const nlohmann::json::invalid_iterator& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Invalid JSON: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
        res.set_content(errorJson.dump(), "application/json");
    }
    catch (const nlohmann::json::type_error& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Invalid JSON: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
        res.set_content(errorJson.dump(), "application/json");
    }
    catch (const nlohmann::json::out_of_range& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Invalid JSON: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
        res.set_content(errorJson.dump(), "application/json");
    }
    catch (const nlohmann::json::other_error& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Invalid JSON: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
        res.set_content(errorJson.dump(), "application/json");
    }
}

void Pet::handlePetpetIdPostRequest([[maybe_unused]] const httplib::Request& req, httplib::Response& res, std::shared_ptr<AuthenticationManager> auth)
{
    try
    {
        if (!performAuthentication(req, auth, res))
        {
            nlohmann::json errorJson = nlohmann::json::object();
            errorJson["message"] = "Authentication required";
            res.status = HTTP_RESPONSE_CODE_UNAUTHORIZED;
            res.set_content(errorJson.dump(), "application/json");
            return;
        }

        PetpetIdPostRequest params;
        std::vector<std::string> paramErrors;
        if (!parsePetpetIdPostParams(req, params, paramErrors))
        {
            nlohmann::json errorJson = nlohmann::json::object();
            errorJson["message"] = "Invalid parameters";
            errorJson["errors"] = paramErrors;
            res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
            res.set_content(errorJson.dump(), "application/json");
            return;
        }

        handlePostForPetpetId(params);
        res.status = HTTP_RESPONSE_CODE_NO_CONTENT;

    }
    catch (const std::exception& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Internal error: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_INTERNAL_SERVER_ERROR;
        res.set_content(errorJson.dump(), "application/json");
    }
}

void Pet::handlePetpetIduploadImagePostRequest([[maybe_unused]] const httplib::Request& req, httplib::Response& res, std::shared_ptr<AuthenticationManager> auth)
{
    try
    {
        if (!performAuthentication(req, auth, res))
        {
            nlohmann::json errorJson = nlohmann::json::object();
            errorJson["message"] = "Authentication required";
            res.status = HTTP_RESPONSE_CODE_UNAUTHORIZED;
            res.set_content(errorJson.dump(), "application/json");
            return;
        }

        PetpetIduploadImagePostRequest params;
        std::vector<std::string> paramErrors;
        if (!parsePetpetIduploadImagePostParams(req, params, paramErrors))
        {
            nlohmann::json errorJson = nlohmann::json::object();
            errorJson["message"] = "Invalid parameters";
            errorJson["errors"] = paramErrors;
            res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
            res.set_content(errorJson.dump(), "application/json");
            return;
        }
        auto result = handlePostForPetpetIduploadImage(params);
        handlePetpetIduploadImagePostResponse(result, res);

    }
    catch (const std::exception& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Internal error: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_INTERNAL_SERVER_ERROR;
        res.set_content(errorJson.dump(), "application/json");
    }
}


void Pet::registerRoutes(httplib::Server& svr, std::shared_ptr<AuthenticationManager> auth)
{
    svr.Post("/pet", [this, auth]([[maybe_unused]] const httplib::Request& req, httplib::Response& res)
    {
        handlePetPostRequest(req, res, auth);
    });
    svr.Delete("/pet/([^/]+)", [this, auth]([[maybe_unused]] const httplib::Request& req, httplib::Response& res)
    {
        handlePetpetIdDeleteRequest(req, res, auth);
    });
    svr.Get("/pet/findByStatus", [this, auth]([[maybe_unused]] const httplib::Request& req, httplib::Response& res)
    {
        handlePetfindByStatusGetRequest(req, res, auth);
    });
    svr.Get("/pet/findByTags", [this, auth]([[maybe_unused]] const httplib::Request& req, httplib::Response& res)
    {
        handlePetfindByTagsGetRequest(req, res, auth);
    });
    svr.Get("/pet/([^/]+)", [this, auth]([[maybe_unused]] const httplib::Request& req, httplib::Response& res)
    {
        handlePetpetIdGetRequest(req, res, auth);
    });
    svr.Put("/pet", [this, auth]([[maybe_unused]] const httplib::Request& req, httplib::Response& res)
    {
        handlePetPutRequest(req, res, auth);
    });
    svr.Post("/pet/([^/]+)", [this, auth]([[maybe_unused]] const httplib::Request& req, httplib::Response& res)
    {
        handlePetpetIdPostRequest(req, res, auth);
    });
    svr.Post("/pet/([^/]+)/uploadImage", [this, auth]([[maybe_unused]] const httplib::Request& req, httplib::Response& res)
    {
        handlePetpetIduploadImagePostRequest(req, res, auth);
    });
}

} // namespace Api