/**
* This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#pragma once

// System headers
#include <httplib.h>
#include <memory>
#include <variant>
#include <optional>

// Project headers
#include "models/ApiResponse.h"
#include "models/Pet.h"

namespace Api {
    class AuthenticationManager;
class Pet {
public:
    Pet() = default;
    virtual ~Pet() = default;
    /**
     * @brief Register all routes for this API
     * @param svr The httplib::Server instance to register routes on
     * @param auth The AuthenticationManager for authentication (optional, defaults to nullptr)
     */
    void registerRoutes(httplib::Server& svr, std::shared_ptr<AuthenticationManager> auth = nullptr);
    // =========================
    // ===== Request types =====
    // =========================

    /**
    * @brief Request type for handlePostForPet.
    */
    struct PetPostRequest
    {
        models::Pet m_request; //Request Body (required)
    };

    /**
    * @brief Request type for handleDeleteForPetpetId.
    */
    struct PetpetIdDeleteRequest
    {
        std::optional<std::string> m_apiKey; //HeaderParams (optional)
        long m_petId; //PathParams (always required)
    };

    /**
    * @brief Request type for handleGetForPetfindByStatus.
    */
    struct PetfindByStatusGetRequest
    {
        std::vector<std::string> m_status; //Query Params (required)
    };

    /**
    * @brief Request type for handleGetForPetfindByTags.
    */
    struct PetfindByTagsGetRequest
    {
        std::vector<std::string> m_tags; //Query Params (required)
    };

    /**
    * @brief Request type for handleGetForPetpetId.
    */
    struct PetpetIdGetRequest
    {
        long m_petId; //PathParams (always required)
    };

    /**
    * @brief Request type for handlePutForPet.
    */
    struct PetPutRequest
    {
        models::Pet m_request; //Request Body (required)
    };

    /**
    * @brief Request type for handlePostForPetpetId.
    */
    struct PetpetIdPostRequest
    {
        long m_petId; //PathParams (always required)
    };

    /**
    * @brief Request type for handlePostForPetpetIduploadImage.
    */
    struct PetpetIduploadImagePostRequest
    {
        long m_petId; //PathParams (always required)
    };

    // ==========================
    // ===== Response types =====
    // ==========================

    /**
    * @brief Response type for handlePostForPet.
    */
    using PetPostResponse = models::Pet;

    /**
    * @brief Response type for handleGetForPetfindByStatus.
    */
    using PetfindByStatusGetResponse = models::Pet;

    /**
    * @brief Response type for handleGetForPetfindByTags.
    */
    using PetfindByTagsGetResponse = models::Pet;

    /**
    * @brief Response type for handleGetForPetpetId.
    */
    using PetpetIdGetResponse = models::Pet;

    /**
    * @brief Response type for handlePutForPet.
    */
    using PetPutResponse = models::Pet;

    /**
    * @brief Response type for handlePostForPetpetIduploadImage.
    */
    using PetpetIduploadImagePostResponse = models::ApiResponse;
    // ============================================================
    // ===== Pure virtual functions to be handled by the user =====
    // ============================================================
    /**
     * PetPostRequest - struct containing all the query parameters and headers and schemas as available.
     * @return PetPostResponse The response type returned by the handler.
     */
    virtual PetPostResponse handlePostForPet(const PetPostRequest& params)=0;

    /**
     * PetpetIdDeleteRequest - struct containing all the query parameters and headers and schemas as available.
     */
    virtual void handleDeleteForPetpetId(const PetpetIdDeleteRequest& params)=0;

    /**
     * PetfindByStatusGetRequest - struct containing all the query parameters and headers and schemas as available.
     * @return PetfindByStatusGetResponse The response type returned by the handler.
     */
    virtual PetfindByStatusGetResponse handleGetForPetfindByStatus(const PetfindByStatusGetRequest& params)=0;

    /**
     * PetfindByTagsGetRequest - struct containing all the query parameters and headers and schemas as available.
     * @return PetfindByTagsGetResponse The response type returned by the handler.
     */
    virtual PetfindByTagsGetResponse handleGetForPetfindByTags(const PetfindByTagsGetRequest& params)=0;

    /**
     * PetpetIdGetRequest - struct containing all the query parameters and headers and schemas as available.
     * @return PetpetIdGetResponse The response type returned by the handler.
     */
    virtual PetpetIdGetResponse handleGetForPetpetId(const PetpetIdGetRequest& params)=0;

    /**
     * PetPutRequest - struct containing all the query parameters and headers and schemas as available.
     * @return PetPutResponse The response type returned by the handler.
     */
    virtual PetPutResponse handlePutForPet(const PetPutRequest& params)=0;

    /**
     * PetpetIdPostRequest - struct containing all the query parameters and headers and schemas as available.
     */
    virtual void handlePostForPetpetId(const PetpetIdPostRequest& params)=0;

    /**
     * PetpetIduploadImagePostRequest - struct containing all the query parameters and headers and schemas as available.
     * @return PetpetIduploadImagePostResponse The response type returned by the handler.
     */
    virtual PetpetIduploadImagePostResponse handlePostForPetpetIduploadImage(const PetpetIduploadImagePostRequest& params)=0;

private:
    // ========================================
    // ===== Helper function declarations =====
    // ========================================
    static bool parsePetPostParams(const httplib::Request& req, PetPostRequest& params, std::vector<std::string>& paramErrors);
    void handlePetPostRequest(const httplib::Request& req, httplib::Response& res, std::shared_ptr<AuthenticationManager> auth);
    static void handlePetPostResponse(const PetPostResponse& result, httplib::Response& res);
    static bool parsePetpetIdDeleteParams(const httplib::Request& req, PetpetIdDeleteRequest& params, std::vector<std::string>& paramErrors);
    void handlePetpetIdDeleteRequest(const httplib::Request& req, httplib::Response& res, std::shared_ptr<AuthenticationManager> auth);
    static bool parsePetfindByStatusGetParams(const httplib::Request& req, PetfindByStatusGetRequest& params, std::vector<std::string>& paramErrors);
    void handlePetfindByStatusGetRequest(const httplib::Request& req, httplib::Response& res, std::shared_ptr<AuthenticationManager> auth);
    static void handlePetfindByStatusGetResponse(const PetfindByStatusGetResponse& result, httplib::Response& res);
    static bool parsePetfindByTagsGetParams(const httplib::Request& req, PetfindByTagsGetRequest& params, std::vector<std::string>& paramErrors);
    void handlePetfindByTagsGetRequest(const httplib::Request& req, httplib::Response& res, std::shared_ptr<AuthenticationManager> auth);
    static void handlePetfindByTagsGetResponse(const PetfindByTagsGetResponse& result, httplib::Response& res);
    static bool parsePetpetIdGetParams(const httplib::Request& req, PetpetIdGetRequest& params, std::vector<std::string>& paramErrors);
    void handlePetpetIdGetRequest(const httplib::Request& req, httplib::Response& res, std::shared_ptr<AuthenticationManager> auth);
    static void handlePetpetIdGetResponse(const PetpetIdGetResponse& result, httplib::Response& res);
    static bool parsePetPutParams(const httplib::Request& req, PetPutRequest& params, std::vector<std::string>& paramErrors);
    void handlePetPutRequest(const httplib::Request& req, httplib::Response& res, std::shared_ptr<AuthenticationManager> auth);
    static void handlePetPutResponse(const PetPutResponse& result, httplib::Response& res);
    static bool parsePetpetIdPostParams(const httplib::Request& req, PetpetIdPostRequest& params, std::vector<std::string>& paramErrors);
    void handlePetpetIdPostRequest(const httplib::Request& req, httplib::Response& res, std::shared_ptr<AuthenticationManager> auth);
    static bool parsePetpetIduploadImagePostParams(const httplib::Request& req, PetpetIduploadImagePostRequest& params, std::vector<std::string>& paramErrors);
    void handlePetpetIduploadImagePostRequest(const httplib::Request& req, httplib::Response& res, std::shared_ptr<AuthenticationManager> auth);
    static void handlePetpetIduploadImagePostResponse(const PetpetIduploadImagePostResponse& result, httplib::Response& res);
    static bool performAuthentication(
        const httplib::Request& req,
        std::shared_ptr<AuthenticationManager> auth,
        httplib::Response& res);
};

} // namespace Api