/**
* This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

// System headers
#include <algorithm>
#include <cctype>
#include <locale>

// Project headers
#include "StoreApi.h"
#include "AuthenticationManager.h"

constexpr int HTTP_RESPONSE_CODE_PRIMITIVE_INTEGER = 200;
constexpr int HTTP_RESPONSE_CODE_ORDER = 200;
constexpr int HTTP_RESPONSE_CODE_NO_CONTENT = 204;
constexpr int HTTP_RESPONSE_CODE_BAD_REQUEST = 400;
constexpr int HTTP_RESPONSE_CODE_UNAUTHORIZED = 401;
constexpr int HTTP_RESPONSE_CODE_INTERNAL_SERVER_ERROR = 500;

namespace Api {

using namespace models;

bool Store::parseStoreorderorderIdDeleteParams(const httplib::Request& req, Store::StoreorderorderIdDeleteRequest& params, std::vector<std::string>& paramErrors)
{
    std::vector<std::string> errors;

    // Path Parameters - orderId (index: 1)
    if (req.matches.size() < 1 + 1)
    {
        errors.push_back("Missing path parameter 'orderId'");
    }
    else
    {
        try
        {
            params.m_orderId = req.matches[1];
        }
        catch (const std::exception& e)
        {
            errors.push_back("Invalid path parameter 'orderId': " + std::string(e.what()));
        }
    }

    // Return errors via out-parameter, return false if any errors
    if (!errors.empty())
    {
        paramErrors = std::move(errors);
        return false;
    }
    return true;
}
void Store::handleStoreinventoryGetResponse(const StoreinventoryGetResponse& result, httplib::Response& res)
{
    // Single response type
    res.status = HTTP_RESPONSE_CODE_PRIMITIVE_INTEGER;
    nlohmann::json responseJson;
    to_json(responseJson, result);
    res.set_content(responseJson.dump(), "application/json");
}
bool Store::parseStoreorderorderIdGetParams(const httplib::Request& req, Store::StoreorderorderIdGetRequest& params, std::vector<std::string>& paramErrors)
{
    std::vector<std::string> errors;

    // Path Parameters - orderId (index: 1)
    if (req.matches.size() < 1 + 1)
    {
        errors.push_back("Missing path parameter 'orderId'");
    }
    else
    {
        try
        {
            params.m_orderId = std::stoll(req.matches[1]);
        }
        catch (const std::exception& e)
        {
            errors.push_back("Invalid path parameter 'orderId': " + std::string(e.what()));
        }
    }

    // Return errors via out-parameter, return false if any errors
    if (!errors.empty())
    {
        paramErrors = std::move(errors);
        return false;
    }
    return true;
}
void Store::handleStoreorderorderIdGetResponse(const StoreorderorderIdGetResponse& result, httplib::Response& res)
{
    // Single response type
    res.status = HTTP_RESPONSE_CODE_ORDER;
    nlohmann::json responseJson;
    to_json(responseJson, result);
    res.set_content(responseJson.dump(), "application/json");
}
bool Store::parseStoreorderPostParams(const httplib::Request& req, Store::StoreorderPostRequest& params, std::vector<std::string>& paramErrors)
{
    std::vector<std::string> errors;

    if (!req.body.empty())
    {
        try
        {
            nlohmann::json json = nlohmann::json::parse(req.body);
            from_json(json, params.m_request);
        }
        catch (const std::exception& e)
        {
            errors.push_back("Invalid request body: " + std::string(e.what()));
        }
    }
    else
    {
        errors.push_back("Missing required request body");
    }

    // Return errors via out-parameter, return false if any errors
    if (!errors.empty())
    {
        paramErrors = std::move(errors);
        return false;
    }
    return true;
}
void Store::handleStoreorderPostResponse(const StoreorderPostResponse& result, httplib::Response& res)
{
    // Single response type
    res.status = HTTP_RESPONSE_CODE_ORDER;
    nlohmann::json responseJson;
    to_json(responseJson, result);
    res.set_content(responseJson.dump(), "application/json");
}

bool Store::performAuthentication(
    const httplib::Request& req,
    std::shared_ptr<AuthenticationManager> auth,
    httplib::Response& res)
{
    if (!auth)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "AuthenticationManager not configured";
        res.status = HTTP_RESPONSE_CODE_INTERNAL_SERVER_ERROR;
        res.set_content(errorJson.dump(), "application/json");
        return false;
    }

    if (req.has_header("api_key"))
    {
        if (auth->validateApiKey(req.get_header_value("api_key"))) return true;
    }




    return false;
}

void Store::handleStoreorderorderIdDeleteRequest([[maybe_unused]] const httplib::Request& req, httplib::Response& res)
{
    try
    {

        StoreorderorderIdDeleteRequest params;
        std::vector<std::string> paramErrors;
        if (!parseStoreorderorderIdDeleteParams(req, params, paramErrors))
        {
            nlohmann::json errorJson = nlohmann::json::object();
            errorJson["message"] = "Invalid parameters";
            errorJson["errors"] = paramErrors;
            res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
            res.set_content(errorJson.dump(), "application/json");
            return;
        }

        handleDeleteForStoreorderorderId(params);
        res.status = HTTP_RESPONSE_CODE_NO_CONTENT;

    }
    catch (const std::exception& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Internal error: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_INTERNAL_SERVER_ERROR;
        res.set_content(errorJson.dump(), "application/json");
    }
}

void Store::handleStoreinventoryGetRequest([[maybe_unused]] const httplib::Request& req, httplib::Response& res, std::shared_ptr<AuthenticationManager> auth)
{
    try
    {
        if (!performAuthentication(req, auth, res))
        {
            nlohmann::json errorJson = nlohmann::json::object();
            errorJson["message"] = "Authentication required";
            res.status = HTTP_RESPONSE_CODE_UNAUTHORIZED;
            res.set_content(errorJson.dump(), "application/json");
            return;
        }

        auto result = handleGetForStoreinventory();
        handleStoreinventoryGetResponse(result, res);

    }
    catch (const std::exception& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Internal error: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_INTERNAL_SERVER_ERROR;
        res.set_content(errorJson.dump(), "application/json");
    }
}

void Store::handleStoreorderorderIdGetRequest([[maybe_unused]] const httplib::Request& req, httplib::Response& res)
{
    try
    {

        StoreorderorderIdGetRequest params;
        std::vector<std::string> paramErrors;
        if (!parseStoreorderorderIdGetParams(req, params, paramErrors))
        {
            nlohmann::json errorJson = nlohmann::json::object();
            errorJson["message"] = "Invalid parameters";
            errorJson["errors"] = paramErrors;
            res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
            res.set_content(errorJson.dump(), "application/json");
            return;
        }
        auto result = handleGetForStoreorderorderId(params);
        handleStoreorderorderIdGetResponse(result, res);

    }
    catch (const std::exception& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Internal error: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_INTERNAL_SERVER_ERROR;
        res.set_content(errorJson.dump(), "application/json");
    }
}

void Store::handleStoreorderPostRequest([[maybe_unused]] const httplib::Request& req, httplib::Response& res)
{
    try
    {

        StoreorderPostRequest params;
        std::vector<std::string> paramErrors;
        if (!parseStoreorderPostParams(req, params, paramErrors))
        {
            nlohmann::json errorJson = nlohmann::json::object();
            errorJson["message"] = "Invalid parameters";
            errorJson["errors"] = paramErrors;
            res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
            res.set_content(errorJson.dump(), "application/json");
            return;
        }
        auto result = handlePostForStoreorder(params);
        handleStoreorderPostResponse(result, res);

    }
    catch (const nlohmann::json::parse_error& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Invalid JSON: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
        res.set_content(errorJson.dump(), "application/json");
    }
    catch (const nlohmann::json::invalid_iterator& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Invalid JSON: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
        res.set_content(errorJson.dump(), "application/json");
    }
    catch (const nlohmann::json::type_error& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Invalid JSON: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
        res.set_content(errorJson.dump(), "application/json");
    }
    catch (const nlohmann::json::out_of_range& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Invalid JSON: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
        res.set_content(errorJson.dump(), "application/json");
    }
    catch (const nlohmann::json::other_error& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Invalid JSON: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
        res.set_content(errorJson.dump(), "application/json");
    }
}


void Store::registerRoutes(httplib::Server& svr, std::shared_ptr<AuthenticationManager> auth)
{
    svr.Delete("/store/order/([^/]+)", [this]([[maybe_unused]] const httplib::Request& req, httplib::Response& res)
    {
        handleStoreorderorderIdDeleteRequest(req, res);
    });
    svr.Get("/store/inventory", [this, auth]([[maybe_unused]] const httplib::Request& req, httplib::Response& res)
    {
        handleStoreinventoryGetRequest(req, res, auth);
    });
    svr.Get("/store/order/([^/]+)", [this]([[maybe_unused]] const httplib::Request& req, httplib::Response& res)
    {
        handleStoreorderorderIdGetRequest(req, res);
    });
    svr.Post("/store/order", [this]([[maybe_unused]] const httplib::Request& req, httplib::Response& res)
    {
        handleStoreorderPostRequest(req, res);
    });
}

} // namespace Api