/**
* This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#pragma once

// System headers
#include <httplib.h>
#include <memory>
#include <variant>
#include <optional>

// Project headers
#include "models/Order.h"

namespace Api {
    class AuthenticationManager;
class Store {
public:
    Store() = default;
    virtual ~Store() = default;
    /**
     * @brief Register all routes for this API
     * @param svr The httplib::Server instance to register routes on
     * @param auth The AuthenticationManager for authentication (optional, defaults to nullptr)
     */
    void registerRoutes(httplib::Server& svr, std::shared_ptr<AuthenticationManager> auth = nullptr);
    // =========================
    // ===== Request types =====
    // =========================

    /**
    * @brief Request type for handleDeleteForStoreorderorderId.
    */
    struct StoreorderorderIdDeleteRequest
    {
        std::string m_orderId; //PathParams (always required)
    };

    /**
    * @brief Request type for handleGetForStoreorderorderId.
    */
    struct StoreorderorderIdGetRequest
    {
        long m_orderId; //PathParams (always required)
    };

    /**
    * @brief Request type for handlePostForStoreorder.
    */
    struct StoreorderPostRequest
    {
        models::Order m_request; //Request Body (required)
    };


    /**
    * @brief Response type for handleGetForStoreinventory.
    */
    using StoreinventoryGetResponse = int;

    /**
    * @brief Response type for handleGetForStoreorderorderId.
    */
    using StoreorderorderIdGetResponse = models::Order;

    /**
    * @brief Response type for handlePostForStoreorder.
    */
    using StoreorderPostResponse = models::Order;
    // ============================================================
    // ===== Pure virtual functions to be handled by the user =====
    // ============================================================
    /**
     * StoreorderorderIdDeleteRequest - struct containing all the query parameters and headers and schemas as available.
     */
    virtual void handleDeleteForStoreorderorderId(const StoreorderorderIdDeleteRequest& params)=0;

    /**
     * @return StoreinventoryGetResponse The response type returned by the handler.
     */
    virtual StoreinventoryGetResponse handleGetForStoreinventory()=0;

    /**
     * StoreorderorderIdGetRequest - struct containing all the query parameters and headers and schemas as available.
     * @return StoreorderorderIdGetResponse The response type returned by the handler.
     */
    virtual StoreorderorderIdGetResponse handleGetForStoreorderorderId(const StoreorderorderIdGetRequest& params)=0;

    /**
     * StoreorderPostRequest - struct containing all the query parameters and headers and schemas as available.
     * @return StoreorderPostResponse The response type returned by the handler.
     */
    virtual StoreorderPostResponse handlePostForStoreorder(const StoreorderPostRequest& params)=0;

private:
    // ========================================
    // ===== Helper function declarations =====
    // ========================================
    static bool parseStoreorderorderIdDeleteParams(const httplib::Request& req, StoreorderorderIdDeleteRequest& params, std::vector<std::string>& paramErrors);
    void handleStoreorderorderIdDeleteRequest(const httplib::Request& req, httplib::Response& res);
    void handleStoreinventoryGetRequest(const httplib::Request& req, httplib::Response& res, std::shared_ptr<AuthenticationManager> auth);
    static void handleStoreinventoryGetResponse(const StoreinventoryGetResponse& result, httplib::Response& res);
    static bool parseStoreorderorderIdGetParams(const httplib::Request& req, StoreorderorderIdGetRequest& params, std::vector<std::string>& paramErrors);
    void handleStoreorderorderIdGetRequest(const httplib::Request& req, httplib::Response& res);
    static void handleStoreorderorderIdGetResponse(const StoreorderorderIdGetResponse& result, httplib::Response& res);
    static bool parseStoreorderPostParams(const httplib::Request& req, StoreorderPostRequest& params, std::vector<std::string>& paramErrors);
    void handleStoreorderPostRequest(const httplib::Request& req, httplib::Response& res);
    static void handleStoreorderPostResponse(const StoreorderPostResponse& result, httplib::Response& res);
    static bool performAuthentication(
        const httplib::Request& req,
        std::shared_ptr<AuthenticationManager> auth,
        httplib::Response& res);
};

} // namespace Api