/**
* This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

// System headers
#include <algorithm>
#include <cctype>
#include <locale>

// Project headers
#include "UserApi.h"
#include "AuthenticationManager.h"

constexpr int HTTP_RESPONSE_CODE_USER = 200;
constexpr int HTTP_RESPONSE_CODE_PRIMITIVE_STRING = 200;
constexpr int HTTP_RESPONSE_CODE_NO_CONTENT = 204;
constexpr int HTTP_RESPONSE_CODE_BAD_REQUEST = 400;
constexpr int HTTP_RESPONSE_CODE_UNAUTHORIZED = 401;
constexpr int HTTP_RESPONSE_CODE_INTERNAL_SERVER_ERROR = 500;

namespace Api {

using namespace models;

bool User::parseUserPostParams(const httplib::Request& req, User::UserPostRequest& params, std::vector<std::string>& paramErrors)
{
    std::vector<std::string> errors;

    if (!req.body.empty())
    {
        try
        {
            nlohmann::json json = nlohmann::json::parse(req.body);
            from_json(json, params.m_request);
        }
        catch (const std::exception& e)
        {
            errors.push_back("Invalid request body: " + std::string(e.what()));
        }
    }
    else
    {
        errors.push_back("Missing required request body");
    }

    // Return errors via out-parameter, return false if any errors
    if (!errors.empty())
    {
        paramErrors = std::move(errors);
        return false;
    }
    return true;
}
bool User::parseUsercreateWithArrayPostParams(const httplib::Request& req, User::UsercreateWithArrayPostRequest& params, std::vector<std::string>& paramErrors)
{
    std::vector<std::string> errors;

    if (!req.body.empty())
    {
        try
        {
            nlohmann::json json = nlohmann::json::parse(req.body);
            from_json(json, params.m_request);
        }
        catch (const std::exception& e)
        {
            errors.push_back("Invalid request body: " + std::string(e.what()));
        }
    }
    else
    {
        errors.push_back("Missing required request body");
    }

    // Return errors via out-parameter, return false if any errors
    if (!errors.empty())
    {
        paramErrors = std::move(errors);
        return false;
    }
    return true;
}
bool User::parseUsercreateWithListPostParams(const httplib::Request& req, User::UsercreateWithListPostRequest& params, std::vector<std::string>& paramErrors)
{
    std::vector<std::string> errors;

    if (!req.body.empty())
    {
        try
        {
            nlohmann::json json = nlohmann::json::parse(req.body);
            from_json(json, params.m_request);
        }
        catch (const std::exception& e)
        {
            errors.push_back("Invalid request body: " + std::string(e.what()));
        }
    }
    else
    {
        errors.push_back("Missing required request body");
    }

    // Return errors via out-parameter, return false if any errors
    if (!errors.empty())
    {
        paramErrors = std::move(errors);
        return false;
    }
    return true;
}
bool User::parseUserusernameDeleteParams(const httplib::Request& req, User::UserusernameDeleteRequest& params, std::vector<std::string>& paramErrors)
{
    std::vector<std::string> errors;

    // Path Parameters - username (index: 1)
    if (req.matches.size() < 1 + 1)
    {
        errors.push_back("Missing path parameter 'username'");
    }
    else
    {
        try
        {
            params.m_username = req.matches[1];
        }
        catch (const std::exception& e)
        {
            errors.push_back("Invalid path parameter 'username': " + std::string(e.what()));
        }
    }

    // Return errors via out-parameter, return false if any errors
    if (!errors.empty())
    {
        paramErrors = std::move(errors);
        return false;
    }
    return true;
}
bool User::parseUserusernameGetParams(const httplib::Request& req, User::UserusernameGetRequest& params, std::vector<std::string>& paramErrors)
{
    std::vector<std::string> errors;

    // Path Parameters - username (index: 1)
    if (req.matches.size() < 1 + 1)
    {
        errors.push_back("Missing path parameter 'username'");
    }
    else
    {
        try
        {
            params.m_username = req.matches[1];
        }
        catch (const std::exception& e)
        {
            errors.push_back("Invalid path parameter 'username': " + std::string(e.what()));
        }
    }

    // Return errors via out-parameter, return false if any errors
    if (!errors.empty())
    {
        paramErrors = std::move(errors);
        return false;
    }
    return true;
}
void User::handleUserusernameGetResponse(const UserusernameGetResponse& result, httplib::Response& res)
{
    // Single response type
    res.status = HTTP_RESPONSE_CODE_USER;
    nlohmann::json responseJson;
    to_json(responseJson, result);
    res.set_content(responseJson.dump(), "application/json");
}
bool User::parseUserloginGetParams(const httplib::Request& req, User::UserloginGetRequest& params, std::vector<std::string>& paramErrors)
{
    std::vector<std::string> errors;

    // Query Parameters - username
    if (req.has_param("username"))
    {
        params.m_username = req.get_param_value("username");
    }

    // Query Parameters - password
    if (req.has_param("password"))
    {
        params.m_password = req.get_param_value("password");
    }

    // Return errors via out-parameter, return false if any errors
    if (!errors.empty())
    {
        paramErrors = std::move(errors);
        return false;
    }
    return true;
}
void User::handleUserloginGetResponse(const UserloginGetResponse& result, httplib::Response& res)
{
    // Single response type
    res.status = HTTP_RESPONSE_CODE_PRIMITIVE_STRING;
    nlohmann::json responseJson;
    to_json(responseJson, result);
    res.set_content(responseJson.dump(), "application/json");
}
bool User::parseUserusernamePutParams(const httplib::Request& req, User::UserusernamePutRequest& params, std::vector<std::string>& paramErrors)
{
    std::vector<std::string> errors;

    if (!req.body.empty())
    {
        try
        {
            nlohmann::json json = nlohmann::json::parse(req.body);
            from_json(json, params.m_request);
        }
        catch (const std::exception& e)
        {
            errors.push_back("Invalid request body: " + std::string(e.what()));
        }
    }
    else
    {
        errors.push_back("Missing required request body");
    }

    // Path Parameters - username (index: 1)
    if (req.matches.size() < 1 + 1)
    {
        errors.push_back("Missing path parameter 'username'");
    }
    else
    {
        try
        {
            params.m_username = req.matches[1];
        }
        catch (const std::exception& e)
        {
            errors.push_back("Invalid path parameter 'username': " + std::string(e.what()));
        }
    }

    // Return errors via out-parameter, return false if any errors
    if (!errors.empty())
    {
        paramErrors = std::move(errors);
        return false;
    }
    return true;
}

bool User::performAuthentication(
    const httplib::Request& req,
    std::shared_ptr<AuthenticationManager> auth,
    httplib::Response& res)
{
    if (!auth)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "AuthenticationManager not configured";
        res.status = HTTP_RESPONSE_CODE_INTERNAL_SERVER_ERROR;
        res.set_content(errorJson.dump(), "application/json");
        return false;
    }

    if (req.has_header("api_key"))
    {
        if (auth->validateApiKey(req.get_header_value("api_key"))) return true;
    }




    return false;
}

void User::handleUserPostRequest([[maybe_unused]] const httplib::Request& req, httplib::Response& res, std::shared_ptr<AuthenticationManager> auth)
{
    try
    {
        if (!performAuthentication(req, auth, res))
        {
            nlohmann::json errorJson = nlohmann::json::object();
            errorJson["message"] = "Authentication required";
            res.status = HTTP_RESPONSE_CODE_UNAUTHORIZED;
            res.set_content(errorJson.dump(), "application/json");
            return;
        }

        UserPostRequest params;
        std::vector<std::string> paramErrors;
        if (!parseUserPostParams(req, params, paramErrors))
        {
            nlohmann::json errorJson = nlohmann::json::object();
            errorJson["message"] = "Invalid parameters";
            errorJson["errors"] = paramErrors;
            res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
            res.set_content(errorJson.dump(), "application/json");
            return;
        }

        handlePostForUser(params);
        res.status = HTTP_RESPONSE_CODE_NO_CONTENT;

    }
    catch (const nlohmann::json::parse_error& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Invalid JSON: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
        res.set_content(errorJson.dump(), "application/json");
    }
    catch (const nlohmann::json::invalid_iterator& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Invalid JSON: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
        res.set_content(errorJson.dump(), "application/json");
    }
    catch (const nlohmann::json::type_error& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Invalid JSON: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
        res.set_content(errorJson.dump(), "application/json");
    }
    catch (const nlohmann::json::out_of_range& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Invalid JSON: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
        res.set_content(errorJson.dump(), "application/json");
    }
    catch (const nlohmann::json::other_error& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Invalid JSON: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
        res.set_content(errorJson.dump(), "application/json");
    }
}

void User::handleUsercreateWithArrayPostRequest([[maybe_unused]] const httplib::Request& req, httplib::Response& res, std::shared_ptr<AuthenticationManager> auth)
{
    try
    {
        if (!performAuthentication(req, auth, res))
        {
            nlohmann::json errorJson = nlohmann::json::object();
            errorJson["message"] = "Authentication required";
            res.status = HTTP_RESPONSE_CODE_UNAUTHORIZED;
            res.set_content(errorJson.dump(), "application/json");
            return;
        }

        UsercreateWithArrayPostRequest params;
        std::vector<std::string> paramErrors;
        if (!parseUsercreateWithArrayPostParams(req, params, paramErrors))
        {
            nlohmann::json errorJson = nlohmann::json::object();
            errorJson["message"] = "Invalid parameters";
            errorJson["errors"] = paramErrors;
            res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
            res.set_content(errorJson.dump(), "application/json");
            return;
        }

        handlePostForUsercreateWithArray(params);
        res.status = HTTP_RESPONSE_CODE_NO_CONTENT;

    }
    catch (const nlohmann::json::parse_error& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Invalid JSON: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
        res.set_content(errorJson.dump(), "application/json");
    }
    catch (const nlohmann::json::invalid_iterator& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Invalid JSON: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
        res.set_content(errorJson.dump(), "application/json");
    }
    catch (const nlohmann::json::type_error& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Invalid JSON: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
        res.set_content(errorJson.dump(), "application/json");
    }
    catch (const nlohmann::json::out_of_range& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Invalid JSON: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
        res.set_content(errorJson.dump(), "application/json");
    }
    catch (const nlohmann::json::other_error& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Invalid JSON: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
        res.set_content(errorJson.dump(), "application/json");
    }
}

void User::handleUsercreateWithListPostRequest([[maybe_unused]] const httplib::Request& req, httplib::Response& res, std::shared_ptr<AuthenticationManager> auth)
{
    try
    {
        if (!performAuthentication(req, auth, res))
        {
            nlohmann::json errorJson = nlohmann::json::object();
            errorJson["message"] = "Authentication required";
            res.status = HTTP_RESPONSE_CODE_UNAUTHORIZED;
            res.set_content(errorJson.dump(), "application/json");
            return;
        }

        UsercreateWithListPostRequest params;
        std::vector<std::string> paramErrors;
        if (!parseUsercreateWithListPostParams(req, params, paramErrors))
        {
            nlohmann::json errorJson = nlohmann::json::object();
            errorJson["message"] = "Invalid parameters";
            errorJson["errors"] = paramErrors;
            res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
            res.set_content(errorJson.dump(), "application/json");
            return;
        }

        handlePostForUsercreateWithList(params);
        res.status = HTTP_RESPONSE_CODE_NO_CONTENT;

    }
    catch (const nlohmann::json::parse_error& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Invalid JSON: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
        res.set_content(errorJson.dump(), "application/json");
    }
    catch (const nlohmann::json::invalid_iterator& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Invalid JSON: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
        res.set_content(errorJson.dump(), "application/json");
    }
    catch (const nlohmann::json::type_error& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Invalid JSON: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
        res.set_content(errorJson.dump(), "application/json");
    }
    catch (const nlohmann::json::out_of_range& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Invalid JSON: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
        res.set_content(errorJson.dump(), "application/json");
    }
    catch (const nlohmann::json::other_error& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Invalid JSON: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
        res.set_content(errorJson.dump(), "application/json");
    }
}

void User::handleUserusernameDeleteRequest([[maybe_unused]] const httplib::Request& req, httplib::Response& res, std::shared_ptr<AuthenticationManager> auth)
{
    try
    {
        if (!performAuthentication(req, auth, res))
        {
            nlohmann::json errorJson = nlohmann::json::object();
            errorJson["message"] = "Authentication required";
            res.status = HTTP_RESPONSE_CODE_UNAUTHORIZED;
            res.set_content(errorJson.dump(), "application/json");
            return;
        }

        UserusernameDeleteRequest params;
        std::vector<std::string> paramErrors;
        if (!parseUserusernameDeleteParams(req, params, paramErrors))
        {
            nlohmann::json errorJson = nlohmann::json::object();
            errorJson["message"] = "Invalid parameters";
            errorJson["errors"] = paramErrors;
            res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
            res.set_content(errorJson.dump(), "application/json");
            return;
        }

        handleDeleteForUserusername(params);
        res.status = HTTP_RESPONSE_CODE_NO_CONTENT;

    }
    catch (const std::exception& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Internal error: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_INTERNAL_SERVER_ERROR;
        res.set_content(errorJson.dump(), "application/json");
    }
}

void User::handleUserusernameGetRequest([[maybe_unused]] const httplib::Request& req, httplib::Response& res)
{
    try
    {

        UserusernameGetRequest params;
        std::vector<std::string> paramErrors;
        if (!parseUserusernameGetParams(req, params, paramErrors))
        {
            nlohmann::json errorJson = nlohmann::json::object();
            errorJson["message"] = "Invalid parameters";
            errorJson["errors"] = paramErrors;
            res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
            res.set_content(errorJson.dump(), "application/json");
            return;
        }
        auto result = handleGetForUserusername(params);
        handleUserusernameGetResponse(result, res);

    }
    catch (const std::exception& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Internal error: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_INTERNAL_SERVER_ERROR;
        res.set_content(errorJson.dump(), "application/json");
    }
}

void User::handleUserloginGetRequest([[maybe_unused]] const httplib::Request& req, httplib::Response& res)
{
    try
    {

        UserloginGetRequest params;
        std::vector<std::string> paramErrors;
        if (!parseUserloginGetParams(req, params, paramErrors))
        {
            nlohmann::json errorJson = nlohmann::json::object();
            errorJson["message"] = "Invalid parameters";
            errorJson["errors"] = paramErrors;
            res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
            res.set_content(errorJson.dump(), "application/json");
            return;
        }
        auto result = handleGetForUserlogin(params);
        handleUserloginGetResponse(result, res);

    }
    catch (const std::exception& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Internal error: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_INTERNAL_SERVER_ERROR;
        res.set_content(errorJson.dump(), "application/json");
    }
}

void User::handleUserlogoutGetRequest([[maybe_unused]] const httplib::Request& req, httplib::Response& res, std::shared_ptr<AuthenticationManager> auth)
{
    try
    {
        if (!performAuthentication(req, auth, res))
        {
            nlohmann::json errorJson = nlohmann::json::object();
            errorJson["message"] = "Authentication required";
            res.status = HTTP_RESPONSE_CODE_UNAUTHORIZED;
            res.set_content(errorJson.dump(), "application/json");
            return;
        }

        handleGetForUserlogout();
        res.status = HTTP_RESPONSE_CODE_NO_CONTENT;

    }
    catch (const std::exception& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Internal error: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_INTERNAL_SERVER_ERROR;
        res.set_content(errorJson.dump(), "application/json");
    }
}

void User::handleUserusernamePutRequest([[maybe_unused]] const httplib::Request& req, httplib::Response& res, std::shared_ptr<AuthenticationManager> auth)
{
    try
    {
        if (!performAuthentication(req, auth, res))
        {
            nlohmann::json errorJson = nlohmann::json::object();
            errorJson["message"] = "Authentication required";
            res.status = HTTP_RESPONSE_CODE_UNAUTHORIZED;
            res.set_content(errorJson.dump(), "application/json");
            return;
        }

        UserusernamePutRequest params;
        std::vector<std::string> paramErrors;
        if (!parseUserusernamePutParams(req, params, paramErrors))
        {
            nlohmann::json errorJson = nlohmann::json::object();
            errorJson["message"] = "Invalid parameters";
            errorJson["errors"] = paramErrors;
            res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
            res.set_content(errorJson.dump(), "application/json");
            return;
        }

        handlePutForUserusername(params);
        res.status = HTTP_RESPONSE_CODE_NO_CONTENT;

    }
    catch (const nlohmann::json::parse_error& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Invalid JSON: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
        res.set_content(errorJson.dump(), "application/json");
    }
    catch (const nlohmann::json::invalid_iterator& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Invalid JSON: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
        res.set_content(errorJson.dump(), "application/json");
    }
    catch (const nlohmann::json::type_error& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Invalid JSON: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
        res.set_content(errorJson.dump(), "application/json");
    }
    catch (const nlohmann::json::out_of_range& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Invalid JSON: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
        res.set_content(errorJson.dump(), "application/json");
    }
    catch (const nlohmann::json::other_error& e)
    {
        nlohmann::json errorJson = nlohmann::json::object();
        errorJson["message"] = "Invalid JSON: " + std::string(e.what());
        res.status = HTTP_RESPONSE_CODE_BAD_REQUEST;
        res.set_content(errorJson.dump(), "application/json");
    }
}


void User::registerRoutes(httplib::Server& svr, std::shared_ptr<AuthenticationManager> auth)
{
    svr.Post("/user", [this, auth]([[maybe_unused]] const httplib::Request& req, httplib::Response& res)
    {
        handleUserPostRequest(req, res, auth);
    });
    svr.Post("/user/createWithArray", [this, auth]([[maybe_unused]] const httplib::Request& req, httplib::Response& res)
    {
        handleUsercreateWithArrayPostRequest(req, res, auth);
    });
    svr.Post("/user/createWithList", [this, auth]([[maybe_unused]] const httplib::Request& req, httplib::Response& res)
    {
        handleUsercreateWithListPostRequest(req, res, auth);
    });
    svr.Delete("/user/([^/]+)", [this, auth]([[maybe_unused]] const httplib::Request& req, httplib::Response& res)
    {
        handleUserusernameDeleteRequest(req, res, auth);
    });
    svr.Get("/user/([^/]+)", [this]([[maybe_unused]] const httplib::Request& req, httplib::Response& res)
    {
        handleUserusernameGetRequest(req, res);
    });
    svr.Get("/user/login", [this]([[maybe_unused]] const httplib::Request& req, httplib::Response& res)
    {
        handleUserloginGetRequest(req, res);
    });
    svr.Get("/user/logout", [this, auth]([[maybe_unused]] const httplib::Request& req, httplib::Response& res)
    {
        handleUserlogoutGetRequest(req, res, auth);
    });
    svr.Put("/user/([^/]+)", [this, auth]([[maybe_unused]] const httplib::Request& req, httplib::Response& res)
    {
        handleUserusernamePutRequest(req, res, auth);
    });
}

} // namespace Api