/**
* This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#pragma once

// System headers
#include <httplib.h>
#include <memory>
#include <variant>
#include <optional>

// Project headers
#include "models/User.h"

namespace Api {
    class AuthenticationManager;
class User {
public:
    User() = default;
    virtual ~User() = default;
    /**
     * @brief Register all routes for this API
     * @param svr The httplib::Server instance to register routes on
     * @param auth The AuthenticationManager for authentication (optional, defaults to nullptr)
     */
    void registerRoutes(httplib::Server& svr, std::shared_ptr<AuthenticationManager> auth = nullptr);
    // =========================
    // ===== Request types =====
    // =========================

    /**
    * @brief Request type for handlePostForUser.
    */
    struct UserPostRequest
    {
        models::User m_request; //Request Body (required)
    };

    /**
    * @brief Request type for handlePostForUsercreateWithArray.
    */
    struct UsercreateWithArrayPostRequest
    {
        models::User m_request; //Request Body (required)
    };

    /**
    * @brief Request type for handlePostForUsercreateWithList.
    */
    struct UsercreateWithListPostRequest
    {
        models::User m_request; //Request Body (required)
    };

    /**
    * @brief Request type for handleDeleteForUserusername.
    */
    struct UserusernameDeleteRequest
    {
        std::string m_username; //PathParams (always required)
    };

    /**
    * @brief Request type for handleGetForUserusername.
    */
    struct UserusernameGetRequest
    {
        std::string m_username; //PathParams (always required)
    };

    /**
    * @brief Request type for handleGetForUserlogin.
    */
    struct UserloginGetRequest
    {
        std::string m_username; //Query Params (required)
        std::string m_password; //Query Params (required)
    };

    /**
    * @brief Request type for handlePutForUserusername.
    */
    struct UserusernamePutRequest
    {
        models::User m_request; //Request Body (required)
        std::string m_username; //PathParams (always required)
    };


    /**
    * @brief Response type for handleGetForUserusername.
    */
    using UserusernameGetResponse = models::User;

    /**
    * @brief Response type for handleGetForUserlogin.
    */
    using UserloginGetResponse = std::string;
    // ============================================================
    // ===== Pure virtual functions to be handled by the user =====
    // ============================================================
    /**
     * UserPostRequest - struct containing all the query parameters and headers and schemas as available.
     */
    virtual void handlePostForUser(const UserPostRequest& params)=0;

    /**
     * UsercreateWithArrayPostRequest - struct containing all the query parameters and headers and schemas as available.
     */
    virtual void handlePostForUsercreateWithArray(const UsercreateWithArrayPostRequest& params)=0;

    /**
     * UsercreateWithListPostRequest - struct containing all the query parameters and headers and schemas as available.
     */
    virtual void handlePostForUsercreateWithList(const UsercreateWithListPostRequest& params)=0;

    /**
     * UserusernameDeleteRequest - struct containing all the query parameters and headers and schemas as available.
     */
    virtual void handleDeleteForUserusername(const UserusernameDeleteRequest& params)=0;

    /**
     * UserusernameGetRequest - struct containing all the query parameters and headers and schemas as available.
     * @return UserusernameGetResponse The response type returned by the handler.
     */
    virtual UserusernameGetResponse handleGetForUserusername(const UserusernameGetRequest& params)=0;

    /**
     * UserloginGetRequest - struct containing all the query parameters and headers and schemas as available.
     * @return UserloginGetResponse The response type returned by the handler.
     */
    virtual UserloginGetResponse handleGetForUserlogin(const UserloginGetRequest& params)=0;

    /**
     */
    virtual void handleGetForUserlogout()=0;

    /**
     * UserusernamePutRequest - struct containing all the query parameters and headers and schemas as available.
     */
    virtual void handlePutForUserusername(const UserusernamePutRequest& params)=0;

private:
    // ========================================
    // ===== Helper function declarations =====
    // ========================================
    static bool parseUserPostParams(const httplib::Request& req, UserPostRequest& params, std::vector<std::string>& paramErrors);
    void handleUserPostRequest(const httplib::Request& req, httplib::Response& res, std::shared_ptr<AuthenticationManager> auth);
    static bool parseUsercreateWithArrayPostParams(const httplib::Request& req, UsercreateWithArrayPostRequest& params, std::vector<std::string>& paramErrors);
    void handleUsercreateWithArrayPostRequest(const httplib::Request& req, httplib::Response& res, std::shared_ptr<AuthenticationManager> auth);
    static bool parseUsercreateWithListPostParams(const httplib::Request& req, UsercreateWithListPostRequest& params, std::vector<std::string>& paramErrors);
    void handleUsercreateWithListPostRequest(const httplib::Request& req, httplib::Response& res, std::shared_ptr<AuthenticationManager> auth);
    static bool parseUserusernameDeleteParams(const httplib::Request& req, UserusernameDeleteRequest& params, std::vector<std::string>& paramErrors);
    void handleUserusernameDeleteRequest(const httplib::Request& req, httplib::Response& res, std::shared_ptr<AuthenticationManager> auth);
    static bool parseUserusernameGetParams(const httplib::Request& req, UserusernameGetRequest& params, std::vector<std::string>& paramErrors);
    void handleUserusernameGetRequest(const httplib::Request& req, httplib::Response& res);
    static void handleUserusernameGetResponse(const UserusernameGetResponse& result, httplib::Response& res);
    static bool parseUserloginGetParams(const httplib::Request& req, UserloginGetRequest& params, std::vector<std::string>& paramErrors);
    void handleUserloginGetRequest(const httplib::Request& req, httplib::Response& res);
    static void handleUserloginGetResponse(const UserloginGetResponse& result, httplib::Response& res);
    void handleUserlogoutGetRequest(const httplib::Request& req, httplib::Response& res, std::shared_ptr<AuthenticationManager> auth);
    static bool parseUserusernamePutParams(const httplib::Request& req, UserusernamePutRequest& params, std::vector<std::string>& paramErrors);
    void handleUserusernamePutRequest(const httplib::Request& req, httplib::Response& res, std::shared_ptr<AuthenticationManager> auth);
    static bool performAuthentication(
        const httplib::Request& req,
        std::shared_ptr<AuthenticationManager> auth,
        httplib::Response& res);
};

} // namespace Api