/**
* This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "ApiResponse.h"

namespace sample::models {

ApiResponse::ApiResponse()
:m_code(
    
        
            
                
                0
)
,m_type(
    
        
            
                ""
                
)
,m_message(
    
        
            
                ""
                
)
{}

nlohmann::json ApiResponse::toJson(const ApiResponse& obj)
{
    nlohmann::json json;
    // code
    json["code"] = obj.getCode();
    // type
    json["type"] = obj.getType();
    // message
    json["message"] = obj.getMessage();
    return json;
}

ApiResponse ApiResponse::fromJson(const nlohmann::json& json)
{
    ApiResponse obj;
    //code 
    if (json.contains("code"))
    {
        auto value = json.at("code" );
    //Not model or Enum
        obj.setCode(value);
    }
    //type 
    if (json.contains("type"))
    {
        auto value = json.at("type" );
    //Not model or Enum
        obj.setType(value);
    }
    //message 
    if (json.contains("message"))
    {
        auto value = json.at("message" );
    //Not model or Enum
        obj.setMessage(value);
    }
    return obj;
}


int ::getCode() const { return m_code; }
void ::setCode(const int& code) { m_code = code; }
std::string ::getType() const { return m_type; }
void ::setType(const std::string& type) { m_type = type; }
std::string ::getMessage() const { return m_message; }
void ::setMessage(const std::string& message) { m_message = message; }

} // namespace sample::models
