/**
* This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "ApiResponse.h"

namespace sample::openapi::models {

ApiResponse::ApiResponse()
: code(0)
, type("")
, message("")
{
}
// =========================================
// ===== Serialization/Deserialization =====
// =========================================
nlohmann::json ApiResponse::toJson(const ApiResponse& obj)
{
    nlohmann::json json = obj;
    return json;
}

ApiResponse ApiResponse::fromJson(const nlohmann::json& json)
{
    ApiResponse obj = json.get<ApiResponse>();
    return obj;
}

// ===================
// ===== Getters =====
// ===================
int ApiResponse::getCode() const
{
    return code;
}
std::string ApiResponse::getType() const
{
    return type;
}
std::string ApiResponse::getMessage() const
{
    return message;
}

// ===================
// ===== Setters =====
// ===================
void ApiResponse::setCode(const int& codeObj)
{
    code = codeObj;
}
void ApiResponse::setType(const std::string& typeObj)
{
    type = typeObj;
}
void ApiResponse::setMessage(const std::string& messageObj)
{
    message = messageObj;
}

} // namespace sample::openapi::models
