/**
* This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#pragma once
#include <nlohmann/json.hpp>
#include <cstdint>

#include <string>

namespace models {


class ApiResponse
{
public:

    ApiResponse();
    virtual ~ApiResponse() = default;

    // JSON serialization
    static nlohmann::json toJson(const ApiResponse& obj);
    static ApiResponse fromJson(const nlohmann::json& json);

    // Getters and setters
    [[nodiscard]] int getCode() const;
    void setCode(const int& code);
    [[nodiscard]] std::string getType() const;
    void setType(const std::string& type);
    [[nodiscard]] std::string getMessage() const;
    void setMessage(const std::string& message);

    // nlohmann::json NLOHMANN_DEFINE_TYPE_INTRUSIVE macro for serialization and deserialization
    // In order to use this macro, member variables must match with the json values, else this MACRO will throw exceptions.
    // Hence the member variables are named exactly as in the json schema.
    // NOTE: If you encounter issues with std::variant (anyOf/oneOf), provide custom to_json/from_json for the union type.
    NLOHMANN_DEFINE_TYPE_INTRUSIVE(ApiResponse, code, type, message)

private:
    int code;
    std::string type;
    std::string message;
};

} // namespace models

