/**
* This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "Category.h"

namespace sample::openapi::models {

Category::Category()
: id(0)
, name("")
{
}
// =========================================
// ===== Serialization/Deserialization =====
// =========================================
nlohmann::json Category::toJson(const Category& obj)
{
    nlohmann::json json = obj;
    return json;
}

Category Category::fromJson(const nlohmann::json& json)
{
    Category obj = json.get<Category>();
    return obj;
}

// ===================
// ===== Getters =====
// ===================
long Category::getId() const
{
    return id;
}
std::string Category::getName() const
{
    return name;
}

// ===================
// ===== Setters =====
// ===================
void Category::setId(const long& idObj)
{
    id = idObj;
}
void Category::setName(const std::string& nameObj)
{
    name = nameObj;
}

} // namespace sample::openapi::models
