/**
* This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#pragma once

#include <nlohmann/json.hpp>


#include <cstdint>
#include <cstdint>

namespace sample::openapi::models {

class Order
{
public:
        // Enum declarations (property-scoped)
    enum class StatusEnum {
                unknown
    };
    static inline  (const std::string& value) {
        if (value.empty()) {
            return ::unknown;
        }
        return ::unknown;
    }
    static inline std::string (const & e) {
        switch (e) {
            case ::unknown: return "unknown";
            default: return "unknown";
        }
    }

    Order();
    virtual ~Order() = default;

    // JSON serialization
    static nlohmann::json toJson(const Order& obj);
    static Order fromJson(const nlohmann::json& json);

    // Getters and setters
    [[nodiscard]] long getId() const;
    void setId(const long& id);
    [[nodiscard]] long getPetId() const;
    void setPetId(const long& petId);
    [[nodiscard]] int getQuantity() const;
    void setQuantity(const int& quantity);
    [[nodiscard]] Date getShipDate() const;
    void setShipDate(const Date& shipDate);
    [[nodiscard]] StatusEnum getStatus() const;
    void setStatus(const StatusEnum& status);
    [[nodiscard]] bool isComplete() const;
    void setComplete(const bool& complete);

private:
    long m_id;
    long m_petId;
    int m_quantity;
    Date m_shipDate;
     m_status;
    bool m_complete;
};

} // namespace sample::openapi::models
