/**
* This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "Order.h"

namespace sample::openapi::models {

Order::Order()
: id(0)
, petId(0)
, quantity(0)
, shipDate("")
, status("")
, complete(false)
{
}
// =========================================
// ===== Serialization/Deserialization =====
// =========================================
nlohmann::json Order::toJson(const Order& obj)
{
    nlohmann::json json = obj;
    return json;
}

Order Order::fromJson(const nlohmann::json& json)
{
    Order obj = json.get<Order>();
    return obj;
}

// ===================
// ===== Getters =====
// ===================
long Order::getId() const
{
    return id;
}
long Order::getPetId() const
{
    return petId;
}
int Order::getQuantity() const
{
    return quantity;
}
std::string Order::getShipDate() const
{
    return shipDate;
}
Status Order::getStatus() const
{
    return status;
}
bool Order::isComplete() const
{
    return complete;
}

// ===================
// ===== Setters =====
// ===================
void Order::setId(const long& idObj)
{
    id = idObj;
}
void Order::setPetId(const long& petIdObj)
{
    petId = petIdObj;
}
void Order::setQuantity(const int& quantityObj)
{
    quantity = quantityObj;
}
void Order::setShipDate(const std::string& shipDateObj)
{
    shipDate = shipDateObj;
}
void Order::setStatus(const Status& statusObj)
{
    status = statusObj;
}
void Order::setComplete(const bool& completeObj)
{
    complete = completeObj;
}

} // namespace sample::openapi::models
