/**
* This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#pragma once
#include <nlohmann/json.hpp>
#include <cstdint>

#include <string>

namespace sample::openapi::models {

class Order
{
public:
    Order();
    virtual ~Order() = default;

    // JSON serialization
    static nlohmann::json toJson(const Order& obj);
    static Order fromJson(const nlohmann::json& json);

    // Getters and setters
    [[nodiscard]] long getId() const;
    void setId(const long& id);
    [[nodiscard]] long getPetId() const;
    void setPetId(const long& petId);
    [[nodiscard]] int getQuantity() const;
    void setQuantity(const int& quantity);
    [[nodiscard]] std::string getShipDate() const;
    void setShipDate(const std::string& shipDate);
    [[nodiscard]] Status getStatus() const;
    void setStatus(const Status& status);
    [[nodiscard]] bool isComplete() const;
    void setComplete(const bool& complete);
    // nlohmann::json NLOHMANN_DEFINE_TYPE_INTRUSIVE macro for serialization and deserialization
    // In order to use this macro, member variables must match with the json values, else this MACRO will throw exceptions.
    // Hence the member variables are named exactly as in the json schema.
    NLOHMANN_DEFINE_TYPE_INTRUSIVE(Order, id, petId, quantity, shipDate, status, complete)
private:

    long id;
    long petId;
    int quantity;
    std::string shipDate;
    Status status;
    bool complete;
};

} // namespace sample::openapi::models
