/**
* This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "Pet.h"

namespace sample::openapi::models {

Pet::Pet()
:m_id(
    
        
            
                
                0
)
,m_category(
    
        Category()
)
,m_name(
    
        
            
                ""
                
)
,m_photoUrls(
    
        
            {}
)
,m_tags(
    
        
            {}
)
,m_status(
    
        
            
                ""
                
)
{}

nlohmann::json Pet::toJson(const Pet& obj)
{
    nlohmann::json json;
    // id
    json["id"] = obj.getId();
    // category
    json["category"] = Category::toJson(obj.getCategory());
    // name
    json["name"] = obj.getName();
    // photoUrls
    // tags
    // status - pet status in the store
    json["status"] = (obj.getStatus());
    return json;
}

Pet Pet::fromJson(const nlohmann::json& json)
{
    Pet obj;
    //id 
    if (json.contains("id"))
    {
        auto value = json.at("id" );
    //Not model or Enum
        obj.setId(value);
    }
    //category 
    if (json.contains("category"))
    {
        auto value = json.at("category" );
        // Model
        if (value.is_object()) {
            obj.setCategory(Category::fromJson(value));
        } else {
            obj.setCategory(Category());
        }
    }
    //name 
    if (json.contains("name"))
    {
        auto value = json.at("name" );
    //Not model or Enum
        obj.setName(value);
    }
    //photoUrls 
    //array
    if(json.contains("photoUrls"))
    {
    //tags 
    //array
    if(json.contains("tags"))
    {
    //status - pet status in the store 
    if (json.contains("status"))
    {
        auto value = json.at("status" );
        // Enum
        if (value.is_string()) {
            obj.setStatus((value.get<std::string>()));
        }
    }
    return obj;
}


long ::getId() const { return m_id; }
void ::setId(const long& id) { m_id = id; }
Category ::getCategory() const { return m_category; }
void ::setCategory(const Category& category) { m_category = category; }
std::string ::getName() const { return m_name; }
void ::setName(const std::string& name) { m_name = name; }
std::vector<std::string> ::getPhotoUrls() const { return m_photoUrls; }
void ::setPhotoUrls(const std::vector<std::string>& photoUrls) { m_photoUrls = photoUrls; }
std::vector<Tag> ::getTags() const { return m_tags; }
void ::setTags(const std::vector<Tag>& tags) { m_tags = tags; }
StatusEnum ::getStatus() const { return m_status; }
void ::setStatus(const StatusEnum& status) { m_status = status; }

} // namespace sample::openapi::models
