/**
* This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#pragma once
#include <nlohmann/json.hpp>
#include "Category.h"

#include "Tag.h"

#include <vector>

#include <string>

namespace sample::openapi::models {

class Pet
{
public:
    Pet();
    virtual ~Pet() = default;

    // JSON serialization
    static nlohmann::json toJson(const Pet& obj);
    static Pet fromJson(const nlohmann::json& json);

    // Getters and setters
    [[nodiscard]] long getId() const;
    void setId(const long& id);
    [[nodiscard]] Category getCategory() const;
    void setCategory(const Category& category);
    [[nodiscard]] std::string getName() const;
    void setName(const std::string& name);
    [[nodiscard]] std::vector<std::string> getPhotoUrls() const;
    void setPhotoUrls(const std::vector<std::string>& photoUrls);
    [[nodiscard]] std::vector<Tag> getTags() const;
    void setTags(const std::vector<Tag>& tags);
    [[nodiscard]] Status getStatus() const;
    void setStatus(const Status& status);
    // nlohmann::json NLOHMANN_DEFINE_TYPE_INTRUSIVE macro for serialization and deserialization
    // In order to use this macro, member variables must match with the json values, else this MACRO will throw exceptions.
    // Hence the member variables are named exactly as in the json schema.
    NLOHMANN_DEFINE_TYPE_INTRUSIVE(Pet, id, category, name, photoUrls, tags, status)
private:

    long id;
    Category category;
    std::string name;
    std::vector<std::string> photoUrls;
    std::vector<Tag> tags;
    Status status;
};

} // namespace sample::openapi::models
