
/**
* This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
#include "Pet.h"

namespace models {

Pet::Pet()
: id(0)
, name("")
, photoUrls(std::vector<std::string>())
, status("")
, category(Category())
, tags(std::vector<Tag>())
{
}
// =========================================
// ===== Serialization/Deserialization =====
// =========================================
nlohmann::json Pet::toJson(const Pet& obj)
{
    nlohmann::json json = obj;
    return json;
}

Pet Pet::fromJson(const nlohmann::json& json)
{
    Pet obj = json.get<Pet>();
    return obj;
}

// ===================
// ===== Getters =====
// ===================
long Pet::getId() const
{
    return id;
}
std::string Pet::getName() const
{
    return name;
}
std::vector<std::string> Pet::getPhotoUrls() const
{
    return photoUrls;
}
PetStatusEnum Pet::getStatus() const
{
    return status;
}
Category Pet::getCategory() const
{
    return category;
}
std::vector<Tag> Pet::getTags() const
{
    return tags;
}

// ===================
// ===== Setters =====
// ===================
void Pet::setId(const long& idObj)
{
    id = idObj;
}
void Pet::setName(const std::string& nameObj)
{
    name = nameObj;
}
void Pet::setPhotoUrls(const std::vector<std::string>& photoUrlsObj)
{
    photoUrls = photoUrlsObj;
}
void Pet::setStatus(const PetStatusEnum& statusObj)
{
    status = statusObj;
}
void Pet::setCategory(const Category& categoryObj)
{
    category = categoryObj;
}
void Pet::setTags(const std::vector<Tag>& tagsObj)
{
    tags = tagsObj;
}

} // namespace models
