/**
* This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#pragma once

#include <nlohmann/json.hpp>

#include "Category.h"
#include "Tag.h"

#include <cstdint>

namespace sample::openapi::models {

class Pet
{
public:
        // Enum declarations (property-scoped)
    enum class StatusEnum {
                unknown
    };
    static inline  (const std::string& value) {
        if (value.empty()) {
            return ::unknown;
        }
        return ::unknown;
    }
    static inline std::string (const & e) {
        switch (e) {
            case ::unknown: return "unknown";
            default: return "unknown";
        }
    }

    Pet();
    virtual ~Pet() = default;

    // JSON serialization
    static nlohmann::json toJson(const Pet& obj);
    static Pet fromJson(const nlohmann::json& json);

    // Getters and setters
    [[nodiscard]] long getId() const;
    void setId(const long& id);
    [[nodiscard]] Category getCategory() const;
    void setCategory(const Category& category);
    [[nodiscard]] std::string getName() const;
    void setName(const std::string& name);
    [[nodiscard]] std::vector<std::string> getPhotoUrls() const;
    void setPhotoUrls(const std::vector<std::string>& photoUrls);
    [[nodiscard]] std::vector<Tag> getTags() const;
    void setTags(const std::vector<Tag>& tags);
    [[nodiscard]] StatusEnum getStatus() const;
    void setStatus(const StatusEnum& status);

private:
    long m_id;
    Category m_category;
    std::string m_name;
    std::vector<std::string> m_photoUrls;
    std::vector<Tag> m_tags;
     m_status;
};

} // namespace sample::openapi::models
