/**
* This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#pragma once
#include <nlohmann/json.hpp>
#include <cstdint>

#include <string>

namespace sample::openapi::models {

class PetError
{
public:
    PetError();
    virtual ~PetError() = default;

    // JSON serialization
    static nlohmann::json toJson(const PetError& obj);
    static PetError fromJson(const nlohmann::json& json);

    // Getters and setters
    [[nodiscard]] int getCode() const;
    void setCode(const int& code);
    [[nodiscard]] std::string getType() const;
    void setType(const std::string& type);
    [[nodiscard]] std::string getMessage() const;
    void setMessage(const std::string& message);
    // nlohmann::json NLOHMANN_DEFINE_TYPE_INTRUSIVE macro for serialization and deserialization
    // In order to use this macro, member variables must match with the json values, else this MACRO will throw exceptions.
    // Hence the member variables are named exactly as in the json schema.
    NLOHMANN_DEFINE_TYPE_INTRUSIVE(PetError, code, type, message)
private:

    int code;
    std::string type;
    std::string message;
};

} // namespace sample::openapi::models
