/**
* This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "PetError.h"

namespace sample::openapi::models {

PetError::PetError()
: code(0)
, type("")
, message("")
{
}
// =========================================
// ===== Serialization/Deserialization =====
// =========================================
nlohmann::json PetError::toJson(const PetError& obj)
{
    nlohmann::json json = obj;
    return json;
}

PetError PetError::fromJson(const nlohmann::json& json)
{
    PetError obj = json.get<PetError>();
    return obj;
}

// ===================
// ===== Getters =====
// ===================
int PetError::getCode() const
{
    return code;
}
std::string PetError::getType() const
{
    return type;
}
std::string PetError::getMessage() const
{
    return message;
}

// ===================
// ===== Setters =====
// ===================
void PetError::setCode(const int& codeObj)
{
    code = codeObj;
}
void PetError::setType(const std::string& typeObj)
{
    type = typeObj;
}
void PetError::setMessage(const std::string& messageObj)
{
    message = messageObj;
}

} // namespace sample::openapi::models
