/**
* This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "Tag.h"

namespace sample::openapi::models {

Tag::Tag()
:m_id(
    
        
            
                
                0
)
,m_name(
    
        
            
                ""
                
)
{}

nlohmann::json Tag::toJson(const Tag& obj)
{
    nlohmann::json json;
    // id
    json["id"] = obj.getId();
    // name
    json["name"] = obj.getName();
    return json;
}

Tag Tag::fromJson(const nlohmann::json& json)
{
    Tag obj;
    //id 
    if (json.contains("id"))
    {
        auto value = json.at("id" );
    //Not model or Enum
        obj.setId(value);
    }
    //name 
    if (json.contains("name"))
    {
        auto value = json.at("name" );
    //Not model or Enum
        obj.setName(value);
    }
    return obj;
}


long ::getId() const { return m_id; }
void ::setId(const long& id) { m_id = id; }
std::string ::getName() const { return m_name; }
void ::setName(const std::string& name) { m_name = name; }

} // namespace sample::openapi::models
