
/**
* This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
#include "Tag.h"

namespace models {

Tag::Tag()
: id(0)
, name("")
{
}
// =========================================
// ===== Serialization/Deserialization =====
// =========================================
nlohmann::json Tag::toJson(const Tag& obj)
{
    nlohmann::json json = obj;
    return json;
}

Tag Tag::fromJson(const nlohmann::json& json)
{
    Tag obj = json.get<Tag>();
    return obj;
}

// ===================
// ===== Getters =====
// ===================
long Tag::getId() const
{
    return id;
}
std::string Tag::getName() const
{
    return name;
}

// ===================
// ===== Setters =====
// ===================
void Tag::setId(const long& idObj)
{
    id = idObj;
}
void Tag::setName(const std::string& nameObj)
{
    name = nameObj;
}

} // namespace models
