/**
* This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#pragma once
#include <nlohmann/json.hpp>
#include <cstdint>

#include <string>

namespace models {


class User
{
public:
    enum class UserStatusEnum {
        _0,
        _1,
        _2
    };

    static std::string EnumToString(UserStatusEnum value) {
        switch (value) {
            case UserUserStatusEnum::_0: return "_0";
            case UserUserStatusEnum::_1: return "_1";
            case UserUserStatusEnum::_2: return "_2";
            default: return {};
        }
    }

    static UserStatusEnum EnumFromString(const std::string& str) {
        if (str == "_0") return UserUserStatusEnum::_0;
        if (str == "_1") return UserUserStatusEnum::_1;
        if (str == "_2") return UserUserStatusEnum::_2;
        throw std::invalid_argument("Invalid enum value");
    }

    User();
    virtual ~User() = default;

    // JSON serialization
    static nlohmann::json toJson(const User& obj);
    static User fromJson(const nlohmann::json& json);

    // Getters and setters
    [[nodiscard]] long getId() const;
    void setId(const long& id);
    [[nodiscard]] std::string getUsername() const;
    void setUsername(const std::string& username);
    [[nodiscard]] std::string getFirstName() const;
    void setFirstName(const std::string& firstName);
    [[nodiscard]] std::string getLastName() const;
    void setLastName(const std::string& lastName);
    [[nodiscard]] std::string getEmail() const;
    void setEmail(const std::string& email);
    [[nodiscard]] std::string getPassword() const;
    void setPassword(const std::string& password);
    [[nodiscard]] std::string getPhone() const;
    void setPhone(const std::string& phone);
    [[nodiscard]] UserUserStatusEnum getUserStatus() const;
    void setUserStatus(const UserUserStatusEnum& userStatus);

    // nlohmann::json NLOHMANN_DEFINE_TYPE_INTRUSIVE macro for serialization and deserialization
    // In order to use this macro, member variables must match with the json values, else this MACRO will throw exceptions.
    // Hence the member variables are named exactly as in the json schema.
    // NOTE: If you encounter issues with std::variant (anyOf/oneOf), provide custom to_json/from_json for the union type.
    NLOHMANN_DEFINE_TYPE_INTRUSIVE(User, id, username, firstName, lastName, email, password, phone, userStatus)

private:
    long id;
    std::string username;
    std::string firstName;
    std::string lastName;
    std::string email;
    std::string password;
    std::string phone;
    UserUserStatusEnum userStatus;
};

} // namespace models

