/**
* This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "User.h"

namespace sample::openapi::models {

User::User()
:m_id(
    
        
            
                
                0
)
,m_username(
    
        
            
                ""
                
)
,m_firstName(
    
        
            
                ""
                
)
,m_lastName(
    
        
            
                ""
                
)
,m_email(
    
        
            
                ""
                
)
,m_password(
    
        
            
                ""
                
)
,m_phone(
    
        
            
                ""
                
)
,m_userStatus(
    
        
            
                
                0
)
{}

nlohmann::json User::toJson(const User& obj)
{
    nlohmann::json json;
    // id
    json["id"] = obj.getId();
    // username
    json["username"] = obj.getUsername();
    // firstName
    json["firstName"] = obj.getFirstName();
    // lastName
    json["lastName"] = obj.getLastName();
    // email
    json["email"] = obj.getEmail();
    // password
    json["password"] = obj.getPassword();
    // phone
    json["phone"] = obj.getPhone();
    // userStatus - User Status
    json["userStatus"] = obj.getUserStatus();
    return json;
}

User User::fromJson(const nlohmann::json& json)
{
    User obj;
    //id 
    if (json.contains("id"))
    {
        auto value = json.at("id" );
    //Not model or Enum
        obj.setId(value);
    }
    //username 
    if (json.contains("username"))
    {
        auto value = json.at("username" );
    //Not model or Enum
        obj.setUsername(value);
    }
    //firstName 
    if (json.contains("firstName"))
    {
        auto value = json.at("firstName" );
    //Not model or Enum
        obj.setFirstName(value);
    }
    //lastName 
    if (json.contains("lastName"))
    {
        auto value = json.at("lastName" );
    //Not model or Enum
        obj.setLastName(value);
    }
    //email 
    if (json.contains("email"))
    {
        auto value = json.at("email" );
    //Not model or Enum
        obj.setEmail(value);
    }
    //password 
    if (json.contains("password"))
    {
        auto value = json.at("password" );
    //Not model or Enum
        obj.setPassword(value);
    }
    //phone 
    if (json.contains("phone"))
    {
        auto value = json.at("phone" );
    //Not model or Enum
        obj.setPhone(value);
    }
    //userStatus - User Status 
    if (json.contains("userStatus"))
    {
        auto value = json.at("userStatus" );
    //Not model or Enum
        obj.setUserStatus(value);
    }
    return obj;
}


long ::getId() const { return m_id; }
void ::setId(const long& id) { m_id = id; }
std::string ::getUsername() const { return m_username; }
void ::setUsername(const std::string& username) { m_username = username; }
std::string ::getFirstName() const { return m_firstName; }
void ::setFirstName(const std::string& firstName) { m_firstName = firstName; }
std::string ::getLastName() const { return m_lastName; }
void ::setLastName(const std::string& lastName) { m_lastName = lastName; }
std::string ::getEmail() const { return m_email; }
void ::setEmail(const std::string& email) { m_email = email; }
std::string ::getPassword() const { return m_password; }
void ::setPassword(const std::string& password) { m_password = password; }
std::string ::getPhone() const { return m_phone; }
void ::setPhone(const std::string& phone) { m_phone = phone; }
int ::getUserStatus() const { return m_userStatus; }
void ::setUserStatus(const int& userStatus) { m_userStatus = userStatus; }

} // namespace sample::openapi::models
