
/**
* This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
#include "TestMultiplePathParameters200Response.h"

namespace models {

TestMultiplePathParameters200Response::TestMultiplePathParameters200Response()
: message("")
{
}
// =========================================
// ===== Getters/Setters =====
// =========================================
// ===================
// ===== Getters =====
// ===================
std::string TestMultiplePathParameters200Response::getMessage() const
{
    return message;
}

// ===================
// ===== Setters =====
// ===================
void TestMultiplePathParameters200Response::setMessage(const std::string& messageObj)
{
    message = messageObj;
}






} // namespace models

