/**
* This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#pragma once

#include <httplib.h>
#include <variant>
#include <optional>

#include "models/ApiResponse.h"
#include "models/ComplexParamsResponse.h"
#include "models/Pet.h"

namespace api {
class Pet {
public:
    Pet() = default;
    virtual ~Pet() = default;
    /**
     * @brief Register all routes for this API
     * @param svr The httplib::Server instance to register routes on
     */
    void registerRoutes(httplib::Server& svr);
    // =========================
    // ===== Request types =====
    // =========================

    /**
    * @brief Request type for handlePostForPet.
    */
    struct PetPostRequest
    {
        std::optional<models::Pet> m_request; //Request Body
    };

    /**
    * @brief Request type for handleGetForPetComplex.
    */
    struct PetComplexGetRequest
    {

        std::optional<DeepObj> m_deepObj; //Query Params (optional)
        std::optional<std::string> m_enumParam; //Query Params (optional)
        std::optional<std::vector<std::string>> m_pipeArr; //Query Params (optional)
        std::optional<std::vector<int>> m_spaceArr; //Query Params (optional)
        std::optional<std::string> m_xEnumHeader; //HeaderParams (optional)
        std::optional<std::string> m_cookieEnum; //Cookies (optional)
    };

    /**
    * @brief Request type for handleDeleteForPetpetId.
    */
    struct PetpetIdDeleteRequest
    {

        std::optional<std::string> m_apiKey; //Query Params (optional)
        long m_petId; //PathParams (always required)
    };

    /**
    * @brief Request type for handleGetForPetFindByStatus.
    */
    struct PetFindByStatusGetRequest
    {

        std::string m_status; //Query Params (required)
    };

    /**
    * @brief Request type for handleGetForPetFindByTags.
    */
    struct PetFindByTagsGetRequest
    {

        std::vector<std::string> m_tags; //Query Params (required)
    };

    /**
    * @brief Request type for handleGetForPetpetId.
    */
    struct PetpetIdGetRequest
    {

        std::optional<std::string> m_customHeader; //HeaderParams (optional)
        long m_petId; //PathParams (always required)
        std::optional<std::string> m_cookieParam; //Cookies (optional)
    };

    /**
    * @brief Request type for handlePutForPet.
    */
    struct PetPutRequest
    {
        std::optional<models::Pet> m_request; //Request Body
    };

    // ==========================
    // ===== Response types =====
    // ==========================

    /**
    * @brief Response type for handlePostForPet.
    */
    using PetPostResponse = std::variant<
                                        models::Pet ,
                                        models::ApiResponse >;

    /**
    * @brief Response type for handleGetForPetComplex.
    */
    using PetComplexGetResponse = std::variant<
                                        models::ComplexParamsResponse>;

    /**
    * @brief Response type for handleGetForPetFindByStatus.
    */
    using PetFindByStatusGetResponse = std::variant<
                                        models::Pet>;

    /**
    * @brief Response type for handleGetForPetFindByTags.
    */
    using PetFindByTagsGetResponse = std::variant<
                                        models::Pet>;

    /**
    * @brief Response type for handleGetForPetpetId.
    */
    using PetpetIdGetResponse = std::variant<
                                        models::Pet ,
                                        models::ApiResponse ,
                                        models::ApiResponse >;
    // ============================================================
    // ===== Pure virtual functions to be handled by the user =====
    // ============================================================
    /**
     * PetPostRequest - struct containing all the query parameters and headers and schemas as available.
     * @return PetPostResponse The response type returned by the handler.
     */
    virtual PetPostResponse handlePostForPet(const PetPostRequest& params)=0;

    /**
     * PetComplexGetRequest - struct containing all the query parameters and headers and schemas as available.
     * @return PetComplexGetResponse The response type returned by the handler.
     */
    virtual PetComplexGetResponse handleGetForPetComplex(const PetComplexGetRequest& params)=0;

    /**
     * PetpetIdDeleteRequest - struct containing all the query parameters and headers and schemas as available.
     */
    virtual void handleDeleteForPetpetId(const PetpetIdDeleteRequest& params)=0;

    /**
     * PetFindByStatusGetRequest - struct containing all the query parameters and headers and schemas as available.
     * @return PetFindByStatusGetResponse The response type returned by the handler.
     */
    virtual PetFindByStatusGetResponse handleGetForPetFindByStatus(const PetFindByStatusGetRequest& params)=0;

    /**
     * PetFindByTagsGetRequest - struct containing all the query parameters and headers and schemas as available.
     * @return PetFindByTagsGetResponse The response type returned by the handler.
     */
    virtual PetFindByTagsGetResponse handleGetForPetFindByTags(const PetFindByTagsGetRequest& params)=0;

    /**
     * PetpetIdGetRequest - struct containing all the query parameters and headers and schemas as available.
     * @return PetpetIdGetResponse The response type returned by the handler.
     */
    virtual PetpetIdGetResponse handleGetForPetpetId(const PetpetIdGetRequest& params)=0;

    /**
     * PetPutRequest - struct containing all the query parameters and headers and schemas as available.
     */
    virtual void handlePutForPet(const PetPutRequest& params)=0;

private:
    // ========================================
    // ===== Helper function declarations =====
    // ========================================
    static bool parsePetParams(const httplib::Request& req, PetPostRequest& params, std::vector<std::string>& paramErrors);
    void handlePetRequest(const httplib::Request& req, httplib::Response& res);
    static void handlePetPostResponse(const PetPostResponse& result, httplib::Response& res);
    static bool parsePetComplexParams(const httplib::Request& req, PetComplexGetRequest& params, std::vector<std::string>& paramErrors);
    void handlePetComplexRequest(const httplib::Request& req, httplib::Response& res);
    static void handlePetComplexGetResponse(const PetComplexGetResponse& result, httplib::Response& res);
    static bool parsePetpetIdParams(const httplib::Request& req, PetpetIdDeleteRequest& params, std::vector<std::string>& paramErrors);
    void handlePetpetIdRequest(const httplib::Request& req, httplib::Response& res);
    static bool parsePetFindByStatusParams(const httplib::Request& req, PetFindByStatusGetRequest& params, std::vector<std::string>& paramErrors);
    void handlePetFindByStatusRequest(const httplib::Request& req, httplib::Response& res);
    static void handlePetFindByStatusGetResponse(const PetFindByStatusGetResponse& result, httplib::Response& res);
    static bool parsePetFindByTagsParams(const httplib::Request& req, PetFindByTagsGetRequest& params, std::vector<std::string>& paramErrors);
    void handlePetFindByTagsRequest(const httplib::Request& req, httplib::Response& res);
    static void handlePetFindByTagsGetResponse(const PetFindByTagsGetResponse& result, httplib::Response& res);
    static bool parsePetpetIdParams(const httplib::Request& req, PetpetIdGetRequest& params, std::vector<std::string>& paramErrors);
    void handlePetpetIdRequest(const httplib::Request& req, httplib::Response& res);
    static void handlePetpetIdGetResponse(const PetpetIdGetResponse& result, httplib::Response& res);
    static bool parsePetParams(const httplib::Request& req, PetPutRequest& params, std::vector<std::string>& paramErrors);
    void handlePetRequest(const httplib::Request& req, httplib::Response& res);
};

} // namespace api