/**
 * This file is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#pragma once
#include "models/List.h"
#include "models/Pet.h"
#include "models/PetError.h"
#include "models/Response.h"
#include <httplib.h>
#include <optional>
#include <variant>

namespace sample::openapi::api {

class Pet {
public:
    Pet() = default;
    virtual ~Pet() = default;
    // Register all the routes with the server instance from derived class.
    void registerRoutes(httplib::Server &svr);
    // ======================================
    // ===== Response type declarations =====
    // ======================================
    // Response type for [petHandlerForPost]
    using PetResponseForPost = std::variant<models::Pet>;

    // Response type for [findByStatusHandlerForGet]
    using FindByStatusResponseForGet = std::variant<models::Pet>;

    // Response type for [findByTagsHandlerForGet]
    using FindByTagsResponseForGet =
        std::variant<models::Pet // success type
                     ,
                     models::PetError>; // error types

    // Response type for [petIdHandlerForGet]
    using PetIdResponseForGet = std::variant<models::Pet>;

    // Response type for [listHandlerForGet]
    using ListResponseForGet = std::variant<models::List>;

    // Response type for [petHandlerForPut]
    using PetResponseForPut = std::variant<models::Pet>;

    // Response type for [petIdUploadImageHandlerForPost]
    using PetIdUploadImageResponseForPost = std::variant<models::Response>;

    // ======================================
    // ===== Request type declarations =====
    // ======================================
    // Request type for [petHandlerForPost]
    struct PetRequestForPost {
      std::optional<models::Pet> m_request;
    };

    // Request type for [petIdHandlerForDelete]
    struct PetIdRequestForDelete {

      long m_petId;
      std::string m_apiKey;
    };

    // Request type for [findByStatusHandlerForGet]
    struct FindByStatusRequestForGet {

      std::vector<std::string> m_status;
    };

    // Request type for [findByTagsHandlerForGet]
    struct FindByTagsRequestForGet {

      std::vector<std::string> m_tags;
    };

    // Request type for [listHandlerForGet]
    struct ListRequestForGet {

      models::Pet::StatusEnum m_status = models::Pet::StatusEnum::unknown;
      long m_categoryId;
      std::vector<long> m_tagIds;
      int m_page;
      int m_pageSize;
    };

    // Request type for [petHandlerForPut]
    struct PetRequestForPut {
      std::optional<models::Pet> m_request;
    };

    // ===== Pure virtual functions to he handled by derived classes =====
    /**
     * @param PetRequestForPost - struct containing all the query parameters and
     * headers and schemas as available.
     * @return PetResponseForPost - The response type returned by the handler.
     */
    virtual PetResponseForPost
    petHandlerForPost(const PetRequestForPost &params) = 0;

    /**
     * @param PetIdRequestForDelete - struct containing all the query parameters
     * and headers and schemas as available.
     */
    virtual void petIdHandlerForDelete(const PetIdRequestForDelete &params) = 0;

    /**
     * @param FindByStatusRequestForGet - struct containing all the query
     * parameters and headers and schemas as available.
     * @return FindByStatusResponseForGet - The response type returned by the
     * handler.
     */
    virtual FindByStatusResponseForGet
    findByStatusHandlerForGet(const FindByStatusRequestForGet &params) = 0;

    /**
     * @param FindByTagsRequestForGet - struct containing all the query
     * parameters and headers and schemas as available.
     * @return FindByTagsResponseForGet - The response type returned by the
     * handler.
     */
    virtual FindByTagsResponseForGet
    findByTagsHandlerForGet(const FindByTagsRequestForGet &params) = 0;

    /**
     * @return PetIdResponseForGet - The response type returned by the handler.
     */
    virtual PetIdResponseForGet petIdHandlerForGet() = 0;

    /**
     * @param ListRequestForGet - struct containing all the query parameters and
     * headers and schemas as available.
     * @return ListResponseForGet - The response type returned by the handler.
     */
    virtual ListResponseForGet
    listHandlerForGet(const ListRequestForGet &params) = 0;

    /**
     * @param PetRequestForPut - struct containing all the query parameters and
     * headers and schemas as available.
     * @return PetResponseForPut - The response type returned by the handler.
     */
    virtual PetResponseForPut
    petHandlerForPut(const PetRequestForPut &params) = 0;

    /**
     */
    virtual void petIdHandlerForPost() = 0;

    /**
     * @return PetIdUploadImageResponseForPost - The response type returned by
     * the handler.
     */
    virtual PetIdUploadImageResponseForPost
    petIdUploadImageHandlerForPost() = 0;

  private:
    // --- Helper function declarations ---
    static PetRequestForPost
    parsePetRequestForPost(const httplib::Request &req);
    static PetIdRequestForDelete
    parsePetIdRequestForDelete(const httplib::Request &req);
    static FindByStatusRequestForGet
    parseFindByStatusRequestForGet(const httplib::Request &req);
    static FindByTagsRequestForGet
    parseFindByTagsRequestForGet(const httplib::Request &req);
    static ListRequestForGet
    parseListRequestForGet(const httplib::Request &req);
    static PetRequestForPut parsePetRequestForPut(const httplib::Request &req);

    static void handlePetResponseForPost(const PetResponseForPost &result,
                                         httplib::Response &res);
    static void
    handleFindByStatusResponseForGet(const FindByStatusResponseForGet &result,
                                     httplib::Response &res);
    static void
    handleFindByTagsResponseForGet(const FindByTagsResponseForGet &result,
                                   httplib::Response &res);
    static void handlePetIdResponseForGet(const PetIdResponseForGet &result,
                                          httplib::Response &res);
    static void handleListResponseForGet(const ListResponseForGet &result,
                                         httplib::Response &res);
    static void handlePetResponseForPut(const PetResponseForPut &result,
                                        httplib::Response &res);
    static void handlePetIdUploadImageResponseForPost(
        const PetIdUploadImageResponseForPost &result, httplib::Response &res);
};

} // namespace sample::openapi::api
