/**
* This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#pragma once

#include "models/ApiResponse.h"
#include "models/Pet.h"
#include "models/PetError400.h"
#include "models/PetError500.h"
#include "models/PetList.h"

#include <httplib.h>
#include <variant>
#include <optional>
namespace sample::openapi::api {
class Pet {
public:
    Pet() = default;
    virtual ~Pet() = default;
    void registerRoutes(httplib::Server& svr);

    // =========================
    // ===== Request types =====
    // =========================

    /**
    * @brief Request type for handlePostForPet.
    */
    struct PetPostRequest
    {
        std::optional<models::Pet> m_request;
        // Query Params not available
        // Header Params not available
    };


    /**
    * @brief Request type for handleDeleteForPetId.
    */
    struct PetIdDeleteRequest
    {
        // No Schema Types defined
        // Query Params not available
        std::string m_apiKey;
    };


    /**
    * @brief Request type for handleGetForFindByStatus.
    */
    struct FindByStatusGetRequest
    {
        // No Schema Types defined
        std::vector<std::string> m_status;
        // Header Params not available
    };


    /**
    * @brief Request type for handleGetForFindByTags.
    */
    struct FindByTagsGetRequest
    {
        // No Schema Types defined
        std::vector<std::string> m_tags;
        // Header Params not available
    };


    /**
    * @brief Request type for handleGetForList.
    */
    struct ListGetRequest
    {
        // No Schema Types defined
        std::string m_status;long m_categoryId;std::vector<long> m_tagIds;int m_page;int m_pageSize;
        // Header Params not available
    };


    /**
    * @brief Request type for handlePutForPet.
    */
    struct PetPutRequest
    {
        std::optional<models::Pet> m_request;
        // Query Params not available
        // Header Params not available
    };


    // ==========================
    // ===== Response types =====
    // ==========================

    /**
    * @brief Response type for handlePostForPet.
    */
    using PetPostResponse = std::variant<
                                 models::Pet>;


    /**
    * @brief Response type for handleGetForFindByStatus.
    */
    using FindByStatusGetResponse = std::variant<
                                 models::Pet>;


    /**
    * @brief Response type for handleGetForFindByTags.
    */
    using FindByTagsGetResponse = std::variant<
                                 models::Pet
                               , models::PetError400
                               , models::PetError500>;


    /**
    * @brief Response type for handleGetForPetId.
    */
    using PetIdGetResponse = std::variant<
                                 models::Pet>;


    /**
    * @brief Response type for handleGetForList.
    */
    using ListGetResponse = std::variant<
                                 models::PetList>;


    /**
    * @brief Response type for handlePutForPet.
    */
    using PetPutResponse = std::variant<
                                 models::Pet>;


    /**
    * @brief Response type for handlePostForPetIdUploadImage.
    */
    using PetIdUploadImagePostResponse = std::variant<
                                 models::ApiResponse>;

    // ============================================================
    // ===== Pure virtual functions to be handled by the user =====
    // ============================================================
    /**
     * PetPostRequest - struct containing all the query parameters and headers and schemas as available.
     * @return PetPostResponse The response type returned by the handler.
     */
    virtual PetPostResponse handlePostForPet(const PetPostRequest& params)=0;

    /**
     * PetIdDeleteRequest - struct containing all the query parameters and headers and schemas as available.
     */
    virtual void handleDeleteForPetId(const PetIdDeleteRequest& params)=0;

    /**
     * FindByStatusGetRequest - struct containing all the query parameters and headers and schemas as available.
     * @return FindByStatusGetResponse The response type returned by the handler.
     */
    virtual FindByStatusGetResponse handleGetForFindByStatus(const FindByStatusGetRequest& params)=0;

    /**
     * FindByTagsGetRequest - struct containing all the query parameters and headers and schemas as available.
     * @return FindByTagsGetResponse The response type returned by the handler.
     */
    virtual FindByTagsGetResponse handleGetForFindByTags(const FindByTagsGetRequest& params)=0;

    /**
     * @return PetIdGetResponse The response type returned by the handler.
     */
    virtual PetIdGetResponse handleGetForPetId()=0;

    /**
     * ListGetRequest - struct containing all the query parameters and headers and schemas as available.
     * @return ListGetResponse The response type returned by the handler.
     */
    virtual ListGetResponse handleGetForList(const ListGetRequest& params)=0;

    /**
     * PetPutRequest - struct containing all the query parameters and headers and schemas as available.
     * @return PetPutResponse The response type returned by the handler.
     */
    virtual PetPutResponse handlePutForPet(const PetPutRequest& params)=0;

    /**
     */
    virtual void handlePostForPetId()=0;

    /**
     * @return PetIdUploadImagePostResponse The response type returned by the handler.
     */
    virtual PetIdUploadImagePostResponse handlePostForPetIdUploadImage()=0;

private:
    // ========================================
    // ===== Helper function declarations =====
    // ========================================
    static PetPostRequest parsePetParams(const httplib::Request& req);
    static void handlePetPostResponse(const PetPostResponse& result, httplib::Response& res);
    static PetIdDeleteRequest parsePetIdParams(const httplib::Request& req);
    static FindByStatusGetRequest parseFindByStatusParams(const httplib::Request& req);
    static void handleFindByStatusGetResponse(const FindByStatusGetResponse& result, httplib::Response& res);
    static FindByTagsGetRequest parseFindByTagsParams(const httplib::Request& req);
    static void handleFindByTagsGetResponse(const FindByTagsGetResponse& result, httplib::Response& res);
    static void handlePetIdGetResponse(const PetIdGetResponse& result, httplib::Response& res);
    static ListGetRequest parseListParams(const httplib::Request& req);
    static void handleListGetResponse(const ListGetResponse& result, httplib::Response& res);
    static PetPutRequest parsePetParams(const httplib::Request& req);
    static void handlePetPutResponse(const PetPutResponse& result, httplib::Response& res);
    static void handlePetIdUploadImagePostResponse(const PetIdUploadImagePostResponse& result, httplib::Response& res);
};

} // namespace sample::openapi::api