/**
* This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "PetApi.h"

constexpr int HTTP_RESPONSE_CODE_PET = 200;
constexpr int HTTP_RESPONSE_CODE_PET_ERROR400 = 400;
constexpr int HTTP_RESPONSE_CODE_PET_ERROR500 = 500;
constexpr int HTTP_RESPONSE_CODE_PET_LIST = 200;
constexpr int HTTP_RESPONSE_CODE_API_RESPONSE = 200;


namespace sample::openapi::api {
Pet::PetPostRequest Pet::parsePetParams(const httplib::Request& req) {
    Pet::PetPostRequest params;
    nlohmann::json json = nlohmann::json::parse(req.body);
    params.m_request = models::Pet::fromJson(json);
    return params;
}
void Pet::handlePetPostResponse(const PetPostResponse& result, httplib::Response& res) {
    std::visit([&](const auto& value) {
        using T = std::decay_t<decltype(value)>;
//Success types
        if constexpr (std::is_same_v<T, models::Pet>) {
            res.status = HTTP_RESPONSE_CODE_PET;
            res.set_content(value.toJson(value).dump(), "application/json");
        }

// No Error types defined
    }, result);
}
Pet::PetIdDeleteRequest Pet::parsePetIdParams(const httplib::Request& req) {
    Pet::PetIdDeleteRequest params;
    return params;
}
Pet::FindByStatusGetRequest Pet::parseFindByStatusParams(const httplib::Request& req) {
    Pet::FindByStatusGetRequest params;
    return params;
}
void Pet::handleFindByStatusGetResponse(const FindByStatusGetResponse& result, httplib::Response& res) {
    std::visit([&](const auto& value) {
        using T = std::decay_t<decltype(value)>;
//Success types
        if constexpr (std::is_same_v<T, models::Pet>) {
            res.status = HTTP_RESPONSE_CODE_PET;
            res.set_content(value.toJson(value).dump(), "application/json");
        }

// No Error types defined
    }, result);
}
Pet::FindByTagsGetRequest Pet::parseFindByTagsParams(const httplib::Request& req) {
    Pet::FindByTagsGetRequest params;
    return params;
}
void Pet::handleFindByTagsGetResponse(const FindByTagsGetResponse& result, httplib::Response& res) {
    std::visit([&](const auto& value) {
        using T = std::decay_t<decltype(value)>;
//Success types
        if constexpr (std::is_same_v<T, models::Pet>) {
            res.status = HTTP_RESPONSE_CODE_PET;
            res.set_content(value.toJson(value).dump(), "application/json");
        }
//Error types
        else if constexpr (std::is_same_v<T, models::PetError400>) {
            res.status = HTTP_RESPONSE_CODE_PET_ERROR400;
            res.set_content(value.toJson(value).dump(), "application/json");
        }
        else if constexpr (std::is_same_v<T, models::PetError500>) {
            res.status = HTTP_RESPONSE_CODE_PET_ERROR500;
            res.set_content(value.toJson(value).dump(), "application/json");
        }

    }, result);
}
void Pet::handlePetIdGetResponse(const PetIdGetResponse& result, httplib::Response& res) {
    std::visit([&](const auto& value) {
        using T = std::decay_t<decltype(value)>;
//Success types
        if constexpr (std::is_same_v<T, models::Pet>) {
            res.status = HTTP_RESPONSE_CODE_PET;
            res.set_content(value.toJson(value).dump(), "application/json");
        }

// No Error types defined
    }, result);
}
Pet::ListGetRequest Pet::parseListParams(const httplib::Request& req) {
    Pet::ListGetRequest params;
    return params;
}
void Pet::handleListGetResponse(const ListGetResponse& result, httplib::Response& res) {
    std::visit([&](const auto& value) {
        using T = std::decay_t<decltype(value)>;
//Success types
        if constexpr (std::is_same_v<T, models::PetList>) {
            res.status = HTTP_RESPONSE_CODE_PET_LIST;
            res.set_content(value.toJson(value).dump(), "application/json");
        }

// No Error types defined
    }, result);
}
Pet::PetPutRequest Pet::parsePetParams(const httplib::Request& req) {
    Pet::PetPutRequest params;
    nlohmann::json json = nlohmann::json::parse(req.body);
    params.m_request = models::Pet::fromJson(json);
    return params;
}
void Pet::handlePetPutResponse(const PetPutResponse& result, httplib::Response& res) {
    std::visit([&](const auto& value) {
        using T = std::decay_t<decltype(value)>;
//Success types
        if constexpr (std::is_same_v<T, models::Pet>) {
            res.status = HTTP_RESPONSE_CODE_PET;
            res.set_content(value.toJson(value).dump(), "application/json");
        }

// No Error types defined
    }, result);
}
void Pet::handlePetIdUploadImagePostResponse(const PetIdUploadImagePostResponse& result, httplib::Response& res) {
    std::visit([&](const auto& value) {
        using T = std::decay_t<decltype(value)>;
//Success types
        if constexpr (std::is_same_v<T, models::ApiResponse>) {
            res.status = HTTP_RESPONSE_CODE_API_RESPONSE;
            res.set_content(value.toJson(value).dump(), "application/json");
        }

// No Error types defined
    }, result);
}

void Pet::registerRoutes(httplib::Server& svr) {
    svr.Post("/pet", [this]([[maybe_unused]]const httplib::Request& req, httplib::Response& res) {
        try {
            auto params = parsePetParams(req);
            auto result = handlePostForPet(params);
            handlePetPostResponse(result, res);
        } catch (const nlohmann::json::parse_error& e) {
            nlohmann::json errorJson = { {"message", "Invalid JSON: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        }  catch (const nlohmann::json::invalid_iterator& e) {
            nlohmann::json errorJson = { {"message", "Invalid JSON: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        } catch (const nlohmann::json::type_error& e) {
            nlohmann::json errorJson = { {"message", "Invalid JSON: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        }  catch (const nlohmann::json::out_of_range& e) {
            nlohmann::json errorJson = { {"message", "Invalid JSON: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        } catch (const nlohmann::json::other_error& e) {
            nlohmann::json errorJson = { {"message", "Invalid JSON: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        }
    });
    svr.Delete("/pet/{petId}", [this]([[maybe_unused]]const httplib::Request& req, httplib::Response& res) {
        try {
            auto params = parsePetIdParams(req);
            auto result = handleDeleteForPetId(params);
        } catch (const std::exception& e) {
            nlohmann::json errorJson = { {"message", "Internal error: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        }
    });
    svr.Get("/pet/findByStatus", [this]([[maybe_unused]]const httplib::Request& req, httplib::Response& res) {
        try {
            auto params = parseFindByStatusParams(req);
            auto result = handleGetForFindByStatus(params);
            handleFindByStatusGetResponse(result, res);
        } catch (const std::exception& e) {
            nlohmann::json errorJson = { {"message", "Internal error: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        }
    });
    svr.Get("/pet/findByTags", [this]([[maybe_unused]]const httplib::Request& req, httplib::Response& res) {
        try {
            auto params = parseFindByTagsParams(req);
            auto result = handleGetForFindByTags(params);
            handleFindByTagsGetResponse(result, res);
        } catch (const std::exception& e) {
            nlohmann::json errorJson = { {"message", "Internal error: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        }
    });
    svr.Get("/pet/{petId}", [this]([[maybe_unused]]const httplib::Request& req, httplib::Response& res) {
        try {
            auto result = handleGetForPetId();
            handlePetIdGetResponse(result, res);
        } catch (const std::exception& e) {
            nlohmann::json errorJson = { {"message", "Internal error: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        }
    });
    svr.Get("/pet/list", [this]([[maybe_unused]]const httplib::Request& req, httplib::Response& res) {
        try {
            auto params = parseListParams(req);
            auto result = handleGetForList(params);
            handleListGetResponse(result, res);
        } catch (const std::exception& e) {
            nlohmann::json errorJson = { {"message", "Internal error: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        }
    });
    svr.Put("/pet", [this]([[maybe_unused]]const httplib::Request& req, httplib::Response& res) {
        try {
            auto params = parsePetParams(req);
            auto result = handlePutForPet(params);
            handlePetPutResponse(result, res);
        } catch (const nlohmann::json::parse_error& e) {
            nlohmann::json errorJson = { {"message", "Invalid JSON: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        }  catch (const nlohmann::json::invalid_iterator& e) {
            nlohmann::json errorJson = { {"message", "Invalid JSON: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        } catch (const nlohmann::json::type_error& e) {
            nlohmann::json errorJson = { {"message", "Invalid JSON: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        }  catch (const nlohmann::json::out_of_range& e) {
            nlohmann::json errorJson = { {"message", "Invalid JSON: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        } catch (const nlohmann::json::other_error& e) {
            nlohmann::json errorJson = { {"message", "Invalid JSON: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        }
    });
    svr.Post("/pet/{petId}", [this]([[maybe_unused]]const httplib::Request& req, httplib::Response& res) {
        try {
            auto result = handlePostForPetId();
        } catch (const std::exception& e) {
            nlohmann::json errorJson = { {"message", "Internal error: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        }
    });
    svr.Post("/pet/{petId}/uploadImage", [this]([[maybe_unused]]const httplib::Request& req, httplib::Response& res) {
        try {
            auto result = handlePostForPetIdUploadImage();
            handlePetIdUploadImagePostResponse(result, res);
        } catch (const std::exception& e) {
            nlohmann::json errorJson = { {"message", "Internal error: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        }
    });
}

} // namespace sample::openapi::api