/**
* This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#pragma once
#include <httplib.h>
#include <variant>
#include <optional>
#include "models/Order.h"

namespace sample::openapi::api {

class Store {
public:
    Store() = default;
    virtual ~Store() = default;
    // Register all the routes with the server instance from derived class.
    void registerRoutes(httplib::Server& svr);
    // ======================================
    // ===== Response type declarations =====
    // ======================================
    // Response type for [inventoryHandlerForGet]
    using InventoryResponseForGet = std::variant<int>;

    // Response type for [orderOrderIdHandlerForGet]
    using OrderOrderIdResponseForGet = std::variant<models::Order>;

    // Response type for [orderHandlerForPost]
    using OrderResponseForPost = std::variant<models::Order>;

    // ======================================
    // ===== Request type declarations =====
    // ======================================
    // Request type for [orderHandlerForPost]
    struct OrderRequestForPost
    {
      std::optional<models::Order> m_request;
    };

    // ===== Pure virtual functions to he handled by derived classes =====
    /**
     */
    virtual void orderOrderIdHandlerForDelete()=0;

    /**
     * @return InventoryResponseForGet - The response type returned by the handler.
     */
    virtual InventoryResponseForGet inventoryHandlerForGet()=0;

    /**
     * @return OrderOrderIdResponseForGet - The response type returned by the handler.
     */
    virtual OrderOrderIdResponseForGet orderOrderIdHandlerForGet()=0;

    /**
     * @param OrderRequestForPost - struct containing all the query parameters and headers and schemas as available.
     * @return OrderResponseForPost - The response type returned by the handler.
     */
    virtual OrderResponseForPost orderHandlerForPost(const OrderRequestForPost& params)=0;

private:
    // --- Helper function declarations ---
    static OrderRequestForPost parseOrderRequestForPost(const httplib::Request& req);

    static void handleInventoryResponseForGet(const InventoryResponseForGet& result, httplib::Response& res);
    static void handleOrderOrderIdResponseForGet(const OrderOrderIdResponseForGet& result, httplib::Response& res);
    static void handleOrderResponseForPost(const OrderResponseForPost& result, httplib::Response& res);
};

} // namespace sample::openapi::api
