/**
* This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#pragma once

#include "models/Order.h"

#include <httplib.h>
#include <variant>
#include <optional>
namespace sample::openapi::api {
class Store {
public:
    Store() = default;
    virtual ~Store() = default;
    void registerRoutes(httplib::Server& svr);


    /**
    * @brief Request type for handlePostForOrder.
    */
    struct OrderPostRequest
    {
        std::optional<models::Order> m_request;
        // Query Params not available
        // Header Params not available
    };



    /**
    * @brief Response type for handleGetForInventory.
    */
    using InventoryGetResponse = std::variant<
                                 int>;


    /**
    * @brief Response type for handleGetForOrderOrderId.
    */
    using OrderOrderIdGetResponse = std::variant<
                                 models::Order>;


    /**
    * @brief Response type for handlePostForOrder.
    */
    using OrderPostResponse = std::variant<
                                 models::Order>;

    // ============================================================
    // ===== Pure virtual functions to be handled by the user =====
    // ============================================================
    /**
     */
    virtual void handleDeleteForOrderOrderId()=0;

    /**
     * @return InventoryGetResponse The response type returned by the handler.
     */
    virtual InventoryGetResponse handleGetForInventory()=0;

    /**
     * @return OrderOrderIdGetResponse The response type returned by the handler.
     */
    virtual OrderOrderIdGetResponse handleGetForOrderOrderId()=0;

    /**
     * OrderPostRequest - struct containing all the query parameters and headers and schemas as available.
     * @return OrderPostResponse The response type returned by the handler.
     */
    virtual OrderPostResponse handlePostForOrder(const OrderPostRequest& params)=0;

private:
    // ========================================
    // ===== Helper function declarations =====
    // ========================================
    static void handleInventoryGetResponse(const InventoryGetResponse& result, httplib::Response& res);
    static void handleOrderOrderIdGetResponse(const OrderOrderIdGetResponse& result, httplib::Response& res);
    static OrderPostRequest parseOrderParams(const httplib::Request& req);
    static void handleOrderPostResponse(const OrderPostResponse& result, httplib::Response& res);
};

} // namespace sample::openapi::api