/**
* This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "StoreApi.h"

constexpr int HTTP_RESPONSE_CODE_PRIMITIVE_INTEGER = 200;
constexpr int HTTP_RESPONSE_CODE_ORDER = 200;


namespace sample::openapi::api {
void Store::handleInventoryGetResponse(const InventoryGetResponse& result, httplib::Response& res) {
    std::visit([&](const auto& value) {
        using T = std::decay_t<decltype(value)>;
//Success types
        if constexpr (std::is_same_v<T, int>) {
            res.status = HTTP_RESPONSE_CODE_PRIMITIVE_INTEGER;
            res.set_content(value.toJson(value).dump(), "application/json");
        }

// No Error types defined
    }, result);
}
void Store::handleOrderOrderIdGetResponse(const OrderOrderIdGetResponse& result, httplib::Response& res) {
    std::visit([&](const auto& value) {
        using T = std::decay_t<decltype(value)>;
//Success types
        if constexpr (std::is_same_v<T, models::Order>) {
            res.status = HTTP_RESPONSE_CODE_ORDER;
            res.set_content(value.toJson(value).dump(), "application/json");
        }

// No Error types defined
    }, result);
}
Store::OrderPostRequest Store::parseOrderParams(const httplib::Request& req) {
    Store::OrderPostRequest params;
    nlohmann::json json = nlohmann::json::parse(req.body);
    params.m_request = models::Order::fromJson(json);
    return params;
}
void Store::handleOrderPostResponse(const OrderPostResponse& result, httplib::Response& res) {
    std::visit([&](const auto& value) {
        using T = std::decay_t<decltype(value)>;
//Success types
        if constexpr (std::is_same_v<T, models::Order>) {
            res.status = HTTP_RESPONSE_CODE_ORDER;
            res.set_content(value.toJson(value).dump(), "application/json");
        }

// No Error types defined
    }, result);
}

void Store::registerRoutes(httplib::Server& svr) {
    svr.Delete("/store/order/{orderId}", [this]([[maybe_unused]]const httplib::Request& req, httplib::Response& res) {
        try {
            auto result = handleDeleteForOrderOrderId();
        } catch (const std::exception& e) {
            nlohmann::json errorJson = { {"message", "Internal error: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        }
    });
    svr.Get("/store/inventory", [this]([[maybe_unused]]const httplib::Request& req, httplib::Response& res) {
        try {
            auto result = handleGetForInventory();
            handleInventoryGetResponse(result, res);
        } catch (const std::exception& e) {
            nlohmann::json errorJson = { {"message", "Internal error: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        }
    });
    svr.Get("/store/order/{orderId}", [this]([[maybe_unused]]const httplib::Request& req, httplib::Response& res) {
        try {
            auto result = handleGetForOrderOrderId();
            handleOrderOrderIdGetResponse(result, res);
        } catch (const std::exception& e) {
            nlohmann::json errorJson = { {"message", "Internal error: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        }
    });
    svr.Post("/store/order", [this]([[maybe_unused]]const httplib::Request& req, httplib::Response& res) {
        try {
            auto params = parseOrderParams(req);
            auto result = handlePostForOrder(params);
            handleOrderPostResponse(result, res);
        } catch (const nlohmann::json::parse_error& e) {
            nlohmann::json errorJson = { {"message", "Invalid JSON: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        }  catch (const nlohmann::json::invalid_iterator& e) {
            nlohmann::json errorJson = { {"message", "Invalid JSON: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        } catch (const nlohmann::json::type_error& e) {
            nlohmann::json errorJson = { {"message", "Invalid JSON: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        }  catch (const nlohmann::json::out_of_range& e) {
            nlohmann::json errorJson = { {"message", "Invalid JSON: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        } catch (const nlohmann::json::other_error& e) {
            nlohmann::json errorJson = { {"message", "Invalid JSON: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        }
    });
}

} // namespace sample::openapi::api