/**
* This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#pragma once

#include <httplib.h>
#include <variant>
#include <optional>

#include "models/Order.h"

namespace api {
class Store {
public:
    Store() = default;
    virtual ~Store() = default;
    /**
     * @brief Register all routes for this API
     * @param svr The httplib::Server instance to register routes on
     */
    void registerRoutes(httplib::Server& svr);
    // =========================
    // ===== Request types =====
    // =========================

    /**
    * @brief Request type for handleDeleteForStoreOrderorderId.
    */
    struct StoreOrderorderIdDeleteRequest
    {

        long m_orderId; //PathParams (always required)
    };

    /**
    * @brief Request type for handleGetForStoreOrderorderId.
    */
    struct StoreOrderorderIdGetRequest
    {

        long m_orderId; //PathParams (always required)
    };

    /**
    * @brief Request type for handlePostForStoreOrder.
    */
    struct StoreOrderPostRequest
    {
        std::optional<models::Order> m_request; //Request Body
    };


    /**
    * @brief Response type for handleGetForStoreOrderorderId.
    */
    using StoreOrderorderIdGetResponse = std::variant<
                                        models::Order>;

    /**
    * @brief Response type for handlePostForStoreOrder.
    */
    using StoreOrderPostResponse = std::variant<
                                        models::Order>;
    // ============================================================
    // ===== Pure virtual functions to be handled by the user =====
    // ============================================================
    /**
     * StoreOrderorderIdDeleteRequest - struct containing all the query parameters and headers and schemas as available.
     */
    virtual void handleDeleteForStoreOrderorderId(const StoreOrderorderIdDeleteRequest& params)=0;

    /**
     * StoreOrderorderIdGetRequest - struct containing all the query parameters and headers and schemas as available.
     * @return StoreOrderorderIdGetResponse The response type returned by the handler.
     */
    virtual StoreOrderorderIdGetResponse handleGetForStoreOrderorderId(const StoreOrderorderIdGetRequest& params)=0;

    /**
     * StoreOrderPostRequest - struct containing all the query parameters and headers and schemas as available.
     * @return StoreOrderPostResponse The response type returned by the handler.
     */
    virtual StoreOrderPostResponse handlePostForStoreOrder(const StoreOrderPostRequest& params)=0;

private:
    // ========================================
    // ===== Helper function declarations =====
    // ========================================
    static bool parseStoreOrderorderIdParams(const httplib::Request& req, StoreOrderorderIdDeleteRequest& params, std::vector<std::string>& paramErrors);
    void handleStoreOrderorderIdRequest(const httplib::Request& req, httplib::Response& res);
    static bool parseStoreOrderorderIdParams(const httplib::Request& req, StoreOrderorderIdGetRequest& params, std::vector<std::string>& paramErrors);
    void handleStoreOrderorderIdRequest(const httplib::Request& req, httplib::Response& res);
    static void handleStoreOrderorderIdGetResponse(const StoreOrderorderIdGetResponse& result, httplib::Response& res);
    static bool parseStoreOrderParams(const httplib::Request& req, StoreOrderPostRequest& params, std::vector<std::string>& paramErrors);
    void handleStoreOrderRequest(const httplib::Request& req, httplib::Response& res);
    static void handleStoreOrderPostResponse(const StoreOrderPostResponse& result, httplib::Response& res);
};

} // namespace api