/**
* This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#pragma once

#include "models/User.h"

#include <httplib.h>
#include <variant>
#include <optional>
namespace sample::openapi::api {
class User {
public:
    User() = default;
    virtual ~User() = default;
    void registerRoutes(httplib::Server& svr);

    // =========================
    // ===== Request types =====
    // =========================

    /**
    * @brief Request type for handlePostForUser.
    */
    struct UserPostRequest
    {
        std::optional<models::User> m_request;
        // Query Params not available
        // Header Params not available
    };


    /**
    * @brief Request type for handlePostForCreateWithArray.
    */
    struct CreateWithArrayPostRequest
    {
        std::optional<models::User> m_request;
        // Query Params not available
        // Header Params not available
    };


    /**
    * @brief Request type for handlePostForCreateWithList.
    */
    struct CreateWithListPostRequest
    {
        std::optional<models::User> m_request;
        // Query Params not available
        // Header Params not available
    };


    /**
    * @brief Request type for handleGetForLogin.
    */
    struct LoginGetRequest
    {
        // No Schema Types defined
        std::string m_username;std::string m_password;
        // Header Params not available
    };


    /**
    * @brief Request type for handlePutForUsername.
    */
    struct UsernamePutRequest
    {
        std::optional<models::User> m_request;
        // Query Params not available
        // Header Params not available
    };



    /**
    * @brief Response type for handleGetForUsername.
    */
    using UsernameGetResponse = std::variant<
                                 models::User>;


    /**
    * @brief Response type for handleGetForLogin.
    */
    using LoginGetResponse = std::variant<
                                 std::string>;

    // ============================================================
    // ===== Pure virtual functions to be handled by the user =====
    // ============================================================
    /**
     * UserPostRequest - struct containing all the query parameters and headers and schemas as available.
     */
    virtual void handlePostForUser(const UserPostRequest& params)=0;

    /**
     * CreateWithArrayPostRequest - struct containing all the query parameters and headers and schemas as available.
     */
    virtual void handlePostForCreateWithArray(const CreateWithArrayPostRequest& params)=0;

    /**
     * CreateWithListPostRequest - struct containing all the query parameters and headers and schemas as available.
     */
    virtual void handlePostForCreateWithList(const CreateWithListPostRequest& params)=0;

    /**
     */
    virtual void handleDeleteForUsername()=0;

    /**
     * @return UsernameGetResponse The response type returned by the handler.
     */
    virtual UsernameGetResponse handleGetForUsername()=0;

    /**
     * LoginGetRequest - struct containing all the query parameters and headers and schemas as available.
     * @return LoginGetResponse The response type returned by the handler.
     */
    virtual LoginGetResponse handleGetForLogin(const LoginGetRequest& params)=0;

    /**
     */
    virtual void handleGetForLogout()=0;

    /**
     * UsernamePutRequest - struct containing all the query parameters and headers and schemas as available.
     */
    virtual void handlePutForUsername(const UsernamePutRequest& params)=0;

private:
    // ========================================
    // ===== Helper function declarations =====
    // ========================================
    static UserPostRequest parseUserParams(const httplib::Request& req);
    static CreateWithArrayPostRequest parseCreateWithArrayParams(const httplib::Request& req);
    static CreateWithListPostRequest parseCreateWithListParams(const httplib::Request& req);
    static void handleUsernameGetResponse(const UsernameGetResponse& result, httplib::Response& res);
    static LoginGetRequest parseLoginParams(const httplib::Request& req);
    static void handleLoginGetResponse(const LoginGetResponse& result, httplib::Response& res);
    static UsernamePutRequest parseUsernameParams(const httplib::Request& req);
};

} // namespace sample::openapi::api