/**
* This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "UserApi.h"

constexpr int HTTP_RESPONSE_CODE_USER = 200;
constexpr int HTTP_RESPONSE_CODE_PRIMITIVE_STRING = 200;


namespace sample::openapi::api {


//Parse request parameters: [ Post - User ]
User::UserRequestForPost User::parseUserRequestForPost(const httplib::Request& req) {
    User::UserRequestForPost params;
    nlohmann::json json = nlohmann::json::parse(req.body);
    params.m_request = models::User::fromJson(json);

    return params;
}


//Parse request parameters: [ Post - CreateWithArray ]
User::CreateWithArrayRequestForPost User::parseCreateWithArrayRequestForPost(const httplib::Request& req) {
    User::CreateWithArrayRequestForPost params;
    nlohmann::json json = nlohmann::json::parse(req.body);
    params.m_request = models::User::fromJson(json);

    return params;
}


//Parse request parameters: [ Post - CreateWithList ]
User::CreateWithListRequestForPost User::parseCreateWithListRequestForPost(const httplib::Request& req) {
    User::CreateWithListRequestForPost params;
    nlohmann::json json = nlohmann::json::parse(req.body);
    params.m_request = models::User::fromJson(json);

    return params;
}



//Handle for response received: [ Get - Username ]
void User::handleUsernameResponseForGet(const UsernameResponseForGet& result, httplib::Response& res) {
    std::visit([&](const auto& value) {
        using T = std::decay_t<decltype(value)>;
        //Success types
        if constexpr (std::is_same_v<T, models::User>) {
            res.status = HTTP_RESPONSE_CODE_USER;
            res.set_content(value.toJson(value).dump(), "application/json");
        }

    }, result);
}


//Parse request parameters: [ Get - Login ]
User::LoginRequestForGet User::parseLoginRequestForGet(const httplib::Request& req) {
    User::LoginRequestForGet params;
 //Query Params
                                //String
    params.m_username = req.path_params.at("username");
    
     //Query Params
                                //String
    params.m_password = req.path_params.at("password");
    
    

    return params;
}

//Handle for response received: [ Get - Login ]
void User::handleLoginResponseForGet(const LoginResponseForGet& result, httplib::Response& res) {
    std::visit([&](const auto& value) {
        using T = std::decay_t<decltype(value)>;
        //Success types
        if constexpr (std::is_same_v<T, std::string>) {
            res.status = HTTP_RESPONSE_CODE_PRIMITIVE_STRING;
            nlohmann::json j = { {"Response", value} };
            res.set_content(j.dump(4), "application/json");
        }

    }, result);
}



//Parse request parameters: [ Put - Username ]
User::UsernameRequestForPut User::parseUsernameRequestForPut(const httplib::Request& req) {
    User::UsernameRequestForPut params;
    nlohmann::json json = nlohmann::json::parse(req.body);
    params.m_request = models::User::fromJson(json);//Path Params
            //primitive
                        params.m_username = req.path_params.at("username");
    
    

    return params;
}

//Register the server instance with all the endpoints available
void User::registerRoutes(httplib::Server& svr) {
    svr.Post("/user", [this]([[maybe_unused]]const httplib::Request& req, httplib::Response& res) {
        try {
            auto params = parseUserRequestForPost(req);
            userHandlerForPost(params);
        }catch (const nlohmann::json::parse_error& e) {
            nlohmann::json errorJson = { {"message", "Invalid JSON: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        }catch (const nlohmann::json::type_error& e) {
            nlohmann::json errorJson = { {"message", "Invalid type in JSON: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        }
    });
    svr.Post("/user/createWithArray", [this]([[maybe_unused]]const httplib::Request& req, httplib::Response& res) {
        try {
            auto params = parseCreateWithArrayRequestForPost(req);
            createWithArrayHandlerForPost(params);
        }catch (const nlohmann::json::parse_error& e) {
            nlohmann::json errorJson = { {"message", "Invalid JSON: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        }catch (const nlohmann::json::type_error& e) {
            nlohmann::json errorJson = { {"message", "Invalid type in JSON: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        }
    });
    svr.Post("/user/createWithList", [this]([[maybe_unused]]const httplib::Request& req, httplib::Response& res) {
        try {
            auto params = parseCreateWithListRequestForPost(req);
            createWithListHandlerForPost(params);
        }catch (const nlohmann::json::parse_error& e) {
            nlohmann::json errorJson = { {"message", "Invalid JSON: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        }catch (const nlohmann::json::type_error& e) {
            nlohmann::json errorJson = { {"message", "Invalid type in JSON: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        }
    });
    svr.Delete("/user/{username}", [this]([[maybe_unused]]const httplib::Request& req, httplib::Response& res) {
        try {
            usernameHandlerForDelete();
        }catch (const std::exception& e) {
            nlohmann::json errorJson = { {"message", "Internal error: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        }
    });
    svr.Get("/user/{username}", [this]([[maybe_unused]]const httplib::Request& req, httplib::Response& res) {
        try {
            auto result = usernameHandlerForGet();
            handleUsernameResponseForGet(result, res);
        }catch (const std::exception& e) {
            nlohmann::json errorJson = { {"message", "Internal error: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        }
    });
    svr.Get("/user/login", [this]([[maybe_unused]]const httplib::Request& req, httplib::Response& res) {
        try {
            auto params = parseLoginRequestForGet(req);
            auto result = loginHandlerForGet(params);
            handleLoginResponseForGet(result, res);
        }catch (const std::exception& e) {
            nlohmann::json errorJson = { {"message", "Internal error: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        }
    });
    svr.Get("/user/logout", [this]([[maybe_unused]]const httplib::Request& req, httplib::Response& res) {
        try {
            logoutHandlerForGet();
        }catch (const std::exception& e) {
            nlohmann::json errorJson = { {"message", "Internal error: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        }
    });
    svr.Put("/user/{username}", [this]([[maybe_unused]]const httplib::Request& req, httplib::Response& res) {
        try {
            auto params = parseUsernameRequestForPut(req);
            usernameHandlerForPut(params);
        }catch (const nlohmann::json::parse_error& e) {
            nlohmann::json errorJson = { {"message", "Invalid JSON: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        }catch (const nlohmann::json::type_error& e) {
            nlohmann::json errorJson = { {"message", "Invalid type in JSON: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        }
    });
}
//addImplStub is true
void User::userHandlerForPost(const UserRequestForPost& params)
{
    
}
void User::createWithArrayHandlerForPost(const CreateWithArrayRequestForPost& params)
{
    
}
void User::createWithListHandlerForPost(const CreateWithListRequestForPost& params)
{
    
}
void User::usernameHandlerForDelete()
{
    
}
User::UsernameResponseForGet User::usernameHandlerForGet()
{
    models::User response;
    return response;
}
User::LoginResponseForGet User::loginHandlerForGet(const LoginRequestForGet& params)
{
    std::string response;
    return response;
}
void User::logoutHandlerForGet()
{
    
}
void User::usernameHandlerForPut(const UsernameRequestForPut& params)
{
    
}

} // namespace sample::openapi::api
