/**
* This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "UserApi.h"

constexpr int HTTP_RESPONSE_CODE_USER = 200;
constexpr int HTTP_RESPONSE_CODE_PRIMITIVE_STRING = 200;


namespace sample::openapi::api {
User::UserPostRequest User::parseUserParams(const httplib::Request& req) {
    User::UserPostRequest params;
    nlohmann::json json = nlohmann::json::parse(req.body);
    params.m_request = models::User::fromJson(json);
    return params;
}
User::CreateWithArrayPostRequest User::parseCreateWithArrayParams(const httplib::Request& req) {
    User::CreateWithArrayPostRequest params;
    nlohmann::json json = nlohmann::json::parse(req.body);
    params.m_request = models::User::fromJson(json);
    return params;
}
User::CreateWithListPostRequest User::parseCreateWithListParams(const httplib::Request& req) {
    User::CreateWithListPostRequest params;
    nlohmann::json json = nlohmann::json::parse(req.body);
    params.m_request = models::User::fromJson(json);
    return params;
}
void User::handleUsernameGetResponse(const UsernameGetResponse& result, httplib::Response& res) {
    std::visit([&](const auto& value) {
        using T = std::decay_t<decltype(value)>;
//Success types
        if constexpr (std::is_same_v<T, models::User>) {
            res.status = HTTP_RESPONSE_CODE_USER;
            res.set_content(value.toJson(value).dump(), "application/json");
        }

// No Error types defined
    }, result);
}
User::LoginGetRequest User::parseLoginParams(const httplib::Request& req) {
    User::LoginGetRequest params;
    return params;
}
void User::handleLoginGetResponse(const LoginGetResponse& result, httplib::Response& res) {
    std::visit([&](const auto& value) {
        using T = std::decay_t<decltype(value)>;
//Success types
        if constexpr (std::is_same_v<T, std::string>) {
            res.status = HTTP_RESPONSE_CODE_PRIMITIVE_STRING;
            res.set_content(value.toJson(value).dump(), "application/json");
        }

// No Error types defined
    }, result);
}
User::UsernamePutRequest User::parseUsernameParams(const httplib::Request& req) {
    User::UsernamePutRequest params;
    nlohmann::json json = nlohmann::json::parse(req.body);
    params.m_request = models::User::fromJson(json);
    return params;
}

void User::registerRoutes(httplib::Server& svr) {
    svr.Post("/user", [this]([[maybe_unused]]const httplib::Request& req, httplib::Response& res) {
        try {
            auto params = parseUserParams(req);
            auto result = handlePostForUser(params);
        } catch (const nlohmann::json::parse_error& e) {
            nlohmann::json errorJson = { {"message", "Invalid JSON: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        }  catch (const nlohmann::json::invalid_iterator& e) {
            nlohmann::json errorJson = { {"message", "Invalid JSON: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        } catch (const nlohmann::json::type_error& e) {
            nlohmann::json errorJson = { {"message", "Invalid JSON: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        }  catch (const nlohmann::json::out_of_range& e) {
            nlohmann::json errorJson = { {"message", "Invalid JSON: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        } catch (const nlohmann::json::other_error& e) {
            nlohmann::json errorJson = { {"message", "Invalid JSON: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        }
    });
    svr.Post("/user/createWithArray", [this]([[maybe_unused]]const httplib::Request& req, httplib::Response& res) {
        try {
            auto params = parseCreateWithArrayParams(req);
            auto result = handlePostForCreateWithArray(params);
        } catch (const nlohmann::json::parse_error& e) {
            nlohmann::json errorJson = { {"message", "Invalid JSON: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        }  catch (const nlohmann::json::invalid_iterator& e) {
            nlohmann::json errorJson = { {"message", "Invalid JSON: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        } catch (const nlohmann::json::type_error& e) {
            nlohmann::json errorJson = { {"message", "Invalid JSON: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        }  catch (const nlohmann::json::out_of_range& e) {
            nlohmann::json errorJson = { {"message", "Invalid JSON: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        } catch (const nlohmann::json::other_error& e) {
            nlohmann::json errorJson = { {"message", "Invalid JSON: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        }
    });
    svr.Post("/user/createWithList", [this]([[maybe_unused]]const httplib::Request& req, httplib::Response& res) {
        try {
            auto params = parseCreateWithListParams(req);
            auto result = handlePostForCreateWithList(params);
        } catch (const nlohmann::json::parse_error& e) {
            nlohmann::json errorJson = { {"message", "Invalid JSON: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        }  catch (const nlohmann::json::invalid_iterator& e) {
            nlohmann::json errorJson = { {"message", "Invalid JSON: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        } catch (const nlohmann::json::type_error& e) {
            nlohmann::json errorJson = { {"message", "Invalid JSON: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        }  catch (const nlohmann::json::out_of_range& e) {
            nlohmann::json errorJson = { {"message", "Invalid JSON: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        } catch (const nlohmann::json::other_error& e) {
            nlohmann::json errorJson = { {"message", "Invalid JSON: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        }
    });
    svr.Delete("/user/{username}", [this]([[maybe_unused]]const httplib::Request& req, httplib::Response& res) {
        try {
            auto result = handleDeleteForUsername();
        } catch (const std::exception& e) {
            nlohmann::json errorJson = { {"message", "Internal error: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        }
    });
    svr.Get("/user/{username}", [this]([[maybe_unused]]const httplib::Request& req, httplib::Response& res) {
        try {
            auto result = handleGetForUsername();
            handleUsernameGetResponse(result, res);
        } catch (const std::exception& e) {
            nlohmann::json errorJson = { {"message", "Internal error: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        }
    });
    svr.Get("/user/login", [this]([[maybe_unused]]const httplib::Request& req, httplib::Response& res) {
        try {
            auto params = parseLoginParams(req);
            auto result = handleGetForLogin(params);
            handleLoginGetResponse(result, res);
        } catch (const std::exception& e) {
            nlohmann::json errorJson = { {"message", "Internal error: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        }
    });
    svr.Get("/user/logout", [this]([[maybe_unused]]const httplib::Request& req, httplib::Response& res) {
        try {
            auto result = handleGetForLogout();
        } catch (const std::exception& e) {
            nlohmann::json errorJson = { {"message", "Internal error: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        }
    });
    svr.Put("/user/{username}", [this]([[maybe_unused]]const httplib::Request& req, httplib::Response& res) {
        try {
            auto params = parseUsernameParams(req);
            auto result = handlePutForUsername(params);
        } catch (const nlohmann::json::parse_error& e) {
            nlohmann::json errorJson = { {"message", "Invalid JSON: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        }  catch (const nlohmann::json::invalid_iterator& e) {
            nlohmann::json errorJson = { {"message", "Invalid JSON: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        } catch (const nlohmann::json::type_error& e) {
            nlohmann::json errorJson = { {"message", "Invalid JSON: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        }  catch (const nlohmann::json::out_of_range& e) {
            nlohmann::json errorJson = { {"message", "Invalid JSON: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        } catch (const nlohmann::json::other_error& e) {
            nlohmann::json errorJson = { {"message", "Invalid JSON: " + std::string(e.what())} };
            res.set_content(errorJson.dump(), "application/json");
        }
    });
}

} // namespace sample::openapi::api