/**
* This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#pragma once
#include <httplib.h>
#include <variant>
#include <optional>
#include "models/User.h"

namespace sample::openapi::api {

class User {
public:
    User() = default;
    virtual ~User() = default;
    // Register all the routes with the server instance from derived class.
    void registerRoutes(httplib::Server& svr);
    // ======================================
    // ===== Response type declarations =====
    // ======================================
    // Response type for [usernameHandlerForGet]
    using UsernameResponseForGet = std::variant<models::User>;

    // Response type for [loginHandlerForGet]
    using LoginResponseForGet = std::variant<std::string>;

    // ======================================
    // ===== Request type declarations =====
    // ======================================
    // Request type for [userHandlerForPost]
    struct UserRequestForPost
    {
      std::optional<models::User> m_request;
    };

    // Request type for [createWithArrayHandlerForPost]
    struct CreateWithArrayRequestForPost
    {
      std::optional<models::User> m_request;
    };

    // Request type for [createWithListHandlerForPost]
    struct CreateWithListRequestForPost
    {
      std::optional<models::User> m_request;
    };

    // Request type for [loginHandlerForGet]
    struct LoginRequestForGet
    {

        std::string m_username;
        std::string m_password;
    };

    // Request type for [usernameHandlerForPut]
    struct UsernameRequestForPut
    {
      std::optional<models::User> m_request;
        std::string m_username;
    };

    // ===== Pure virtual functions to he handled by derived classes =====
    /**
     * @param UserRequestForPost - struct containing all the query parameters and headers and schemas as available.
     */
    virtual void userHandlerForPost(const UserRequestForPost& params)=0;

    /**
     * @param CreateWithArrayRequestForPost - struct containing all the query parameters and headers and schemas as available.
     */
    virtual void createWithArrayHandlerForPost(const CreateWithArrayRequestForPost& params)=0;

    /**
     * @param CreateWithListRequestForPost - struct containing all the query parameters and headers and schemas as available.
     */
    virtual void createWithListHandlerForPost(const CreateWithListRequestForPost& params)=0;

    /**
     */
    virtual void usernameHandlerForDelete()=0;

    /**
     * @return UsernameResponseForGet - The response type returned by the handler.
     */
    virtual UsernameResponseForGet usernameHandlerForGet()=0;

    /**
     * @param LoginRequestForGet - struct containing all the query parameters and headers and schemas as available.
     * @return LoginResponseForGet - The response type returned by the handler.
     */
    virtual LoginResponseForGet loginHandlerForGet(const LoginRequestForGet& params)=0;

    /**
     */
    virtual void logoutHandlerForGet()=0;

    /**
     * @param UsernameRequestForPut - struct containing all the query parameters and headers and schemas as available.
     */
    virtual void usernameHandlerForPut(const UsernameRequestForPut& params)=0;

private:
    // --- Helper function declarations ---
    static UserRequestForPost parseUserRequestForPost(const httplib::Request& req);
    static CreateWithArrayRequestForPost parseCreateWithArrayRequestForPost(const httplib::Request& req);
    static CreateWithListRequestForPost parseCreateWithListRequestForPost(const httplib::Request& req);
    static LoginRequestForGet parseLoginRequestForGet(const httplib::Request& req);
    static UsernameRequestForPut parseUsernameRequestForPut(const httplib::Request& req);

    static void handleUsernameResponseForGet(const UsernameResponseForGet& result, httplib::Response& res);
    static void handleLoginResponseForGet(const LoginResponseForGet& result, httplib::Response& res);
};

} // namespace sample::openapi::api
