/**
* This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#pragma once

#include <httplib.h>
#include <variant>
#include <optional>

#include "models/User.h"

namespace api {
class User {
public:
    User() = default;
    virtual ~User() = default;
    /**
     * @brief Register all routes for this API
     * @param svr The httplib::Server instance to register routes on
     */
    void registerRoutes(httplib::Server& svr);
    // =========================
    // ===== Request types =====
    // =========================

    /**
    * @brief Request type for handlePostForUser.
    */
    struct UserPostRequest
    {
        std::optional<models::User> m_request; //Request Body
    };

    /**
    * @brief Request type for handleDeleteForUserusername.
    */
    struct UserusernameDeleteRequest
    {

        std::string m_username; //PathParams (always required)
    };

    /**
    * @brief Request type for handleGetForUserusername.
    */
    struct UserusernameGetRequest
    {

        std::string m_username; //PathParams (always required)
    };

    /**
    * @brief Request type for handlePutForUserusername.
    */
    struct UserusernamePutRequest
    {
        std::optional<models::User> m_request; //Request Body
        std::string m_username; //PathParams (always required)
    };

    // ==========================
    // ===== Response types =====
    // ==========================

    /**
    * @brief Response type for handlePostForUser.
    */
    using UserPostResponse = std::variant<
                                        models::User>;

    /**
    * @brief Response type for handleGetForUserusername.
    */
    using UserusernameGetResponse = std::variant<
                                        models::User>;
    // ============================================================
    // ===== Pure virtual functions to be handled by the user =====
    // ============================================================
    /**
     * UserPostRequest - struct containing all the query parameters and headers and schemas as available.
     * @return UserPostResponse The response type returned by the handler.
     */
    virtual UserPostResponse handlePostForUser(const UserPostRequest& params)=0;

    /**
     * UserusernameDeleteRequest - struct containing all the query parameters and headers and schemas as available.
     */
    virtual void handleDeleteForUserusername(const UserusernameDeleteRequest& params)=0;

    /**
     * UserusernameGetRequest - struct containing all the query parameters and headers and schemas as available.
     * @return UserusernameGetResponse The response type returned by the handler.
     */
    virtual UserusernameGetResponse handleGetForUserusername(const UserusernameGetRequest& params)=0;

    /**
     * UserusernamePutRequest - struct containing all the query parameters and headers and schemas as available.
     */
    virtual void handlePutForUserusername(const UserusernamePutRequest& params)=0;

private:
    // ========================================
    // ===== Helper function declarations =====
    // ========================================
    static bool parseUserParams(const httplib::Request& req, UserPostRequest& params, std::vector<std::string>& paramErrors);
    void handleUserRequest(const httplib::Request& req, httplib::Response& res);
    static void handleUserPostResponse(const UserPostResponse& result, httplib::Response& res);
    static bool parseUserusernameParams(const httplib::Request& req, UserusernameDeleteRequest& params, std::vector<std::string>& paramErrors);
    void handleUserusernameRequest(const httplib::Request& req, httplib::Response& res);
    static bool parseUserusernameParams(const httplib::Request& req, UserusernameGetRequest& params, std::vector<std::string>& paramErrors);
    void handleUserusernameRequest(const httplib::Request& req, httplib::Response& res);
    static void handleUserusernameGetResponse(const UserusernameGetResponse& result, httplib::Response& res);
    static bool parseUserusernameParams(const httplib::Request& req, UserusernamePutRequest& params, std::vector<std::string>& paramErrors);
    void handleUserusernameRequest(const httplib::Request& req, httplib::Response& res);
};

} // namespace api